export type BeadFamily =
  | "solid"
  | "pearl"
  | "translucent"
  | "neon"
  | "metallic"
  | "glitter"
  | "glow"
  | "striped"
  | "other";

export interface BeadColor {
  /** Brand color code (Perler product code / chart series code). */
  code: string;
  name: string;
  hex: string;
  family: BeadFamily;
}

export interface Brand {
  label: string;
  /** Bead pitch in mm: 5 = midi, 2.6 = mini. */
  pitchMm: number;
  colors: BeadColor[];
}

// GENERATED FILE — do not edit by hand. Regenerate: node scripts/gen-palette.mjs
//
// Perler: complete current catalog, measured RGB from the community-maintained
// beadcolors dataset (github.com/maxcleme/beadcolors).
// All other systems: complete charts from bitbead.app (www.bitbead.app/en/colors).

export const PERLER_COLORS: BeadColor[] = [
  { code: "80-15213", name: "Apricot", hex: "#F5A168", family: "solid" },
  { code: "80-19018", name: "Black", hex: "#323234", family: "solid" },
  { code: "80-19093", name: "Blueberry Creme", hex: "#85A8E3", family: "solid" },
  { code: "80-19063", name: "Blush", hex: "#F99297", family: "solid" },
  { code: "80-15273", name: "Brick", hex: "#FC9574", family: "solid" },
  { code: "80-19012", name: "Brown", hex: "#674C44", family: "solid" },
  { code: "80-19006", name: "Bubblegum", hex: "#D8729A", family: "solid" },
  { code: "80-19090", name: "Butterscotch", hex: "#DA9964", family: "solid" },
  { code: "80-15266", name: "Caribbean Sea", hex: "#6CC8AD", family: "solid" },
  { code: "80-15276", name: "Carnation Pink", hex: "#F8C7C9", family: "solid" },
  { code: "80-15263", name: "Celery", hex: "#BED4A6", family: "solid" },
  { code: "80-15207", name: "Charcoal", hex: "#4F595A", family: "solid" },
  { code: "80-19057", name: "Cheddar", hex: "#FBB146", family: "solid" },
  { code: "80-15961", name: "Cherry", hex: "#9D2B3A", family: "solid" },
  { code: "80-15200", name: "Cobalt", hex: "#0065B1", family: "solid" },
  { code: "80-15262", name: "Cocoa", hex: "#392928", family: "solid" },
  { code: "80-15272", name: "Coral", hex: "#FF9A8B", family: "solid" },
  { code: "80-15242", name: "Cotton Candy", hex: "#F479B0", family: "solid" },
  { code: "80-19096", name: "Cranapple", hex: "#843947", family: "solid" },
  { code: "80-19002", name: "Creme", hex: "#E1E2BB", family: "solid" },
  { code: "80-19008", name: "Dark Blue", hex: "#0E5092", family: "solid" },
  { code: "80-19010", name: "Dark Green", hex: "#007B4E", family: "solid" },
  { code: "80-19092", name: "Dark Grey", hex: "#585C61", family: "solid" },
  { code: "80-15261", name: "Dark Spruce", hex: "#14313B", family: "solid" },
  { code: "80-15253", name: "Denim", hex: "#4C6388", family: "solid" },
  { code: "80-15248", name: "Eggplant", hex: "#6F3255", family: "solid" },
  { code: "80-15179", name: "Evergreen", hex: "#305545", family: "solid" },
  { code: "80-15205", name: "Fawn", hex: "#C9A385", family: "solid" },
  { code: "80-15219", name: "Fern", hex: "#7F971A", family: "solid" },
  { code: "80-15203", name: "Flamingo", hex: "#F2AFB7", family: "solid" },
  { code: "80-15247", name: "Forest", hex: "#005D57", family: "solid" },
  { code: "80-15267", name: "Frosted Lilac", hex: "#CDB7C3", family: "solid" },
  { code: "80-15256", name: "Fruit Punch", hex: "#CA3B65", family: "solid" },
  { code: "80-15257", name: "Fuchsia", hex: "#CB59B9", family: "solid" },
  { code: "80-15250", name: "Gingerbread", hex: "#7E5446", family: "solid" },
  { code: "80-15243", name: "Grape", hex: "#503B9C", family: "solid" },
  { code: "80-19080", name: "Green", hex: "#4DAB64", family: "solid" },
  { code: "80-19017", name: "Grey", hex: "#909497", family: "solid" },
  { code: "80-15249", name: "Honey", hex: "#DA8C2C", family: "solid" },
  { code: "80-19059", name: "Hot Coral", hex: "#DD595B", family: "solid" },
  { code: "80-15245", name: "Iris", hex: "#4E56A3", family: "solid" },
  { code: "80-19061", name: "Kiwi Lime", hex: "#69B845", family: "solid" },
  { code: "80-15217", name: "Lagoon", hex: "#00A4AC", family: "solid" },
  { code: "80-15182", name: "Lavender", hex: "#AF9FCE", family: "solid" },
  { code: "80-15269", name: "Lemon", hex: "#F6D901", family: "solid" },
  { code: "80-19009", name: "Light Blue", hex: "#278CC9", family: "solid" },
  { code: "80-19021", name: "Light Brown", hex: "#936848", family: "solid" },
  { code: "80-19011", name: "Light Green", hex: "#18C7B1", family: "solid" },
  { code: "80-15181", name: "Light Grey", hex: "#B3BAB8", family: "solid" },
  { code: "80-19079", name: "Light Pink", hex: "#E1BCCE", family: "solid" },
  { code: "80-19038", name: "Magenta", hex: "#E04284", family: "solid" },
  { code: "80-15201", name: "Midnight", hex: "#2F3C55", family: "solid" },
  { code: "80-15240", name: "Mint", hex: "#B3EED5", family: "solid" },
  { code: "80-15215", name: "Mist", hex: "#93B0BD", family: "solid" },
  { code: "80-15239", name: "Mocha", hex: "#C8B693", family: "solid" },
  { code: "80-15258", name: "Mulberry", hex: "#714875", family: "solid" },
  { code: "80-15089", name: "Neon Blue", hex: "#406AE1", family: "neon" },
  { code: "80-15220", name: "Olive", hex: "#696E31", family: "solid" },
  { code: "80-19004", name: "Orange", hex: "#EB7B31", family: "solid" },
  { code: "80-15255", name: "Orange Cream", hex: "#EFB79B", family: "solid" },
  { code: "80-15210", name: "Orchid", hex: "#B1628E", family: "solid" },
  { code: "80-19091", name: "Parrot Green", hex: "#009188", family: "solid" },
  { code: "80-19052", name: "Pastel Blue", hex: "#4A9CCF", family: "solid" },
  { code: "80-19053", name: "Pastel Green", hex: "#6DCC94", family: "solid" },
  { code: "80-19054", name: "Pastel Lavender", hex: "#937FBF", family: "solid" },
  { code: "80-19056", name: "Pastel Yellow", hex: "#E9E290", family: "solid" },
  { code: "80-19033", name: "Peach", hex: "#E9BFB9", family: "solid" },
  { code: "80-15275", name: "Peacock", hex: "#0090AC", family: "solid" },
  { code: "80-19070", name: "Periwinkle Blue", hex: "#6683B7", family: "solid" },
  { code: "80-15206", name: "Pewter", hex: "#94A19D", family: "solid" },
  { code: "80-19083", name: "Pink", hex: "#D45496", family: "solid" },
  { code: "80-19060", name: "Plum", hex: "#A75D9D", family: "solid" },
  { code: "80-19097", name: "Prickly Pear", hex: "#BBC938", family: "solid" },
  { code: "80-19007", name: "Purple", hex: "#684B86", family: "solid" },
  { code: "80-19088", name: "Raspberry", hex: "#983864", family: "solid" },
  { code: "80-19005", name: "Red", hex: "#B0353C", family: "solid" },
  { code: "80-15274", name: "Rich Butter", hex: "#F6CA69", family: "solid" },
  { code: "80-15202", name: "Robin's Egg", hex: "#A9CDD5", family: "solid" },
  { code: "80-15244", name: "Rose", hex: "#D25D72", family: "solid" },
  { code: "80-19020", name: "Rust", hex: "#995043", family: "solid" },
  { code: "80-15254", name: "Sage", hex: "#9AA98E", family: "solid" },
  { code: "80-15204", name: "Salmon", hex: "#E1747A", family: "solid" },
  { code: "80-19098", name: "Sand", hex: "#E5BE9E", family: "solid" },
  { code: "80-15199", name: "Shamrock", hex: "#008F53", family: "solid" },
  { code: "80-15214", name: "Sherbet", hex: "#D8E47C", family: "solid" },
  { code: "80-15216", name: "Sky", hex: "#4AC0D8", family: "solid" },
  { code: "80-15252", name: "Slate Blue", hex: "#5E6D7B", family: "solid" },
  { code: "80-15259", name: "Slime", hex: "#C8C85C", family: "solid" },
  { code: "80-15241", name: "Sour Apple", hex: "#A3DE6F", family: "solid" },
  { code: "80-15212", name: "Spice", hex: "#D9593A", family: "solid" },
  { code: "80-15260", name: "Stone", hex: "#988C8C", family: "solid" },
  { code: "80-15268", name: "Sunflower", hex: "#DEBA0B", family: "solid" },
  { code: "80-19035", name: "Tan", hex: "#C5AC90", family: "solid" },
  { code: "80-15246", name: "Tangerine", hex: "#FD5918", family: "solid" },
  { code: "80-15218", name: "Teal", hex: "#047F8A", family: "solid" },
  { code: "80-15251", name: "Thistle", hex: "#8C8CA7", family: "solid" },
  { code: "80-15208", name: "Toasted Marshmallow", hex: "#DEDACE", family: "solid" },
  { code: "80-15211", name: "Tomato", hex: "#D14337", family: "solid" },
  { code: "80-19058", name: "Toothpaste", hex: "#96D1D4", family: "solid" },
  { code: "80-19062", name: "Turquoise", hex: "#0098C5", family: "solid" },
  { code: "80-15265", name: "Twilight Plum", hex: "#C685B1", family: "solid" },
  { code: "80-19001", name: "White", hex: "#EAEFEE", family: "solid" },
  { code: "80-19003", name: "Yellow", hex: "#E7CE3E", family: "solid" },
];

export const MARD221_COLORS: BeadColor[] = [
  { code: "A1", name: "A1", hex: "#FAF4C8", family: "solid" },
  { code: "A2", name: "A2", hex: "#FFFFD5", family: "solid" },
  { code: "A3", name: "A3", hex: "#FEFF8B", family: "solid" },
  { code: "A4", name: "A4", hex: "#FBED56", family: "solid" },
  { code: "A5", name: "A5", hex: "#F4D738", family: "solid" },
  { code: "A6", name: "A6", hex: "#FEAC4C", family: "solid" },
  { code: "A7", name: "A7", hex: "#FE8B4C", family: "solid" },
  { code: "A8", name: "A8", hex: "#FFDA45", family: "solid" },
  { code: "A9", name: "A9", hex: "#FF995B", family: "solid" },
  { code: "A10", name: "A10", hex: "#F77C31", family: "solid" },
  { code: "A11", name: "A11", hex: "#FFDD99", family: "solid" },
  { code: "A12", name: "A12", hex: "#FE9F72", family: "solid" },
  { code: "A13", name: "A13", hex: "#FFC365", family: "solid" },
  { code: "A14", name: "A14", hex: "#FD543D", family: "solid" },
  { code: "A15", name: "A15", hex: "#FFF365", family: "solid" },
  { code: "A16", name: "A16", hex: "#FFFF9F", family: "solid" },
  { code: "A17", name: "A17", hex: "#FFE36E", family: "solid" },
  { code: "A18", name: "A18", hex: "#FEBE7D", family: "solid" },
  { code: "A19", name: "A19", hex: "#FD7C72", family: "solid" },
  { code: "A20", name: "A20", hex: "#FFD568", family: "solid" },
  { code: "A21", name: "A21", hex: "#FFE395", family: "solid" },
  { code: "A22", name: "A22", hex: "#F4F57D", family: "solid" },
  { code: "A23", name: "A23", hex: "#E6C9B7", family: "solid" },
  { code: "A24", name: "A24", hex: "#F7F8A2", family: "solid" },
  { code: "A25", name: "A25", hex: "#FFD67D", family: "solid" },
  { code: "A26", name: "A26", hex: "#FFC830", family: "solid" },
  { code: "B1", name: "B1", hex: "#E6EE31", family: "solid" },
  { code: "B2", name: "B2", hex: "#63F347", family: "solid" },
  { code: "B3", name: "B3", hex: "#9EF780", family: "solid" },
  { code: "B4", name: "B4", hex: "#5DE035", family: "solid" },
  { code: "B5", name: "B5", hex: "#35E352", family: "solid" },
  { code: "B6", name: "B6", hex: "#65E2A6", family: "solid" },
  { code: "B7", name: "B7", hex: "#3DAF80", family: "solid" },
  { code: "B8", name: "B8", hex: "#1C9C4F", family: "solid" },
  { code: "B9", name: "B9", hex: "#27523A", family: "solid" },
  { code: "B10", name: "B10", hex: "#95D3C2", family: "solid" },
  { code: "B11", name: "B11", hex: "#5D722A", family: "solid" },
  { code: "B12", name: "B12", hex: "#166F41", family: "solid" },
  { code: "B13", name: "B13", hex: "#CAEB7B", family: "solid" },
  { code: "B14", name: "B14", hex: "#ADE946", family: "solid" },
  { code: "B15", name: "B15", hex: "#2E5132", family: "solid" },
  { code: "B16", name: "B16", hex: "#C5ED9C", family: "solid" },
  { code: "B17", name: "B17", hex: "#9BB13A", family: "solid" },
  { code: "B18", name: "B18", hex: "#E6EE49", family: "solid" },
  { code: "B19", name: "B19", hex: "#24B88C", family: "solid" },
  { code: "B20", name: "B20", hex: "#C2F0CC", family: "solid" },
  { code: "B21", name: "B21", hex: "#156A6B", family: "solid" },
  { code: "B22", name: "B22", hex: "#0B3C43", family: "solid" },
  { code: "B23", name: "B23", hex: "#303A21", family: "solid" },
  { code: "B24", name: "B24", hex: "#EEFCA5", family: "solid" },
  { code: "B25", name: "B25", hex: "#4E846D", family: "solid" },
  { code: "B26", name: "B26", hex: "#8D7A35", family: "solid" },
  { code: "B27", name: "B27", hex: "#CCE1AF", family: "solid" },
  { code: "B28", name: "B28", hex: "#9EE5B9", family: "solid" },
  { code: "B29", name: "B29", hex: "#C5E254", family: "solid" },
  { code: "B30", name: "B30", hex: "#E2FCB1", family: "solid" },
  { code: "B31", name: "B31", hex: "#B0E792", family: "solid" },
  { code: "B32", name: "B32", hex: "#9CAB5A", family: "solid" },
  { code: "C1", name: "C1", hex: "#E8FFE7", family: "solid" },
  { code: "C2", name: "C2", hex: "#A9F9FC", family: "solid" },
  { code: "C3", name: "C3", hex: "#A0E2FB", family: "solid" },
  { code: "C4", name: "C4", hex: "#41CCFF", family: "solid" },
  { code: "C5", name: "C5", hex: "#01ACEB", family: "solid" },
  { code: "C6", name: "C6", hex: "#50AAF0", family: "solid" },
  { code: "C7", name: "C7", hex: "#3677D2", family: "solid" },
  { code: "C8", name: "C8", hex: "#0F54C0", family: "solid" },
  { code: "C9", name: "C9", hex: "#324BCA", family: "solid" },
  { code: "C10", name: "C10", hex: "#3EBCE2", family: "solid" },
  { code: "C11", name: "C11", hex: "#28DDDE", family: "solid" },
  { code: "C12", name: "C12", hex: "#1C334D", family: "solid" },
  { code: "C13", name: "C13", hex: "#CDE8FF", family: "solid" },
  { code: "C14", name: "C14", hex: "#D5FDFF", family: "solid" },
  { code: "C15", name: "C15", hex: "#22C4C6", family: "solid" },
  { code: "C16", name: "C16", hex: "#1557A8", family: "solid" },
  { code: "C17", name: "C17", hex: "#04D1F6", family: "solid" },
  { code: "C18", name: "C18", hex: "#1D3344", family: "solid" },
  { code: "C19", name: "C19", hex: "#1887A2", family: "solid" },
  { code: "C20", name: "C20", hex: "#176DAF", family: "solid" },
  { code: "C21", name: "C21", hex: "#BEDDFF", family: "solid" },
  { code: "C22", name: "C22", hex: "#67B4BE", family: "solid" },
  { code: "C23", name: "C23", hex: "#C8E2FF", family: "solid" },
  { code: "C24", name: "C24", hex: "#7CC4FF", family: "solid" },
  { code: "C25", name: "C25", hex: "#A9E5E5", family: "solid" },
  { code: "C26", name: "C26", hex: "#3CAED8", family: "solid" },
  { code: "C27", name: "C27", hex: "#D3DFFA", family: "solid" },
  { code: "C28", name: "C28", hex: "#BBCFED", family: "solid" },
  { code: "C29", name: "C29", hex: "#34488E", family: "solid" },
  { code: "D1", name: "D1", hex: "#AEB4F2", family: "solid" },
  { code: "D2", name: "D2", hex: "#858EDD", family: "solid" },
  { code: "D3", name: "D3", hex: "#2F54AF", family: "solid" },
  { code: "D4", name: "D4", hex: "#182A84", family: "solid" },
  { code: "D5", name: "D5", hex: "#B843C5", family: "solid" },
  { code: "D6", name: "D6", hex: "#AC7BDE", family: "solid" },
  { code: "D7", name: "D7", hex: "#8854B3", family: "solid" },
  { code: "D8", name: "D8", hex: "#E2D3FF", family: "solid" },
  { code: "D9", name: "D9", hex: "#D5B9F8", family: "solid" },
  { code: "D10", name: "D10", hex: "#361851", family: "solid" },
  { code: "D11", name: "D11", hex: "#B9BAE1", family: "solid" },
  { code: "D12", name: "D12", hex: "#DE9AD4", family: "solid" },
  { code: "D13", name: "D13", hex: "#B90095", family: "solid" },
  { code: "D14", name: "D14", hex: "#8B279B", family: "solid" },
  { code: "D15", name: "D15", hex: "#2F1F90", family: "solid" },
  { code: "D16", name: "D16", hex: "#E3E1EE", family: "solid" },
  { code: "D17", name: "D17", hex: "#C4D4F6", family: "solid" },
  { code: "D18", name: "D18", hex: "#A45EC7", family: "solid" },
  { code: "D19", name: "D19", hex: "#D8C3D7", family: "solid" },
  { code: "D20", name: "D20", hex: "#9C32B2", family: "solid" },
  { code: "D21", name: "D21", hex: "#9A009B", family: "solid" },
  { code: "D22", name: "D22", hex: "#333A95", family: "solid" },
  { code: "D23", name: "D23", hex: "#EBDAFC", family: "solid" },
  { code: "D24", name: "D24", hex: "#7786E5", family: "solid" },
  { code: "D25", name: "D25", hex: "#494FC7", family: "solid" },
  { code: "D26", name: "D26", hex: "#DFC2F8", family: "solid" },
  { code: "E1", name: "E1", hex: "#FDD3CC", family: "solid" },
  { code: "E2", name: "E2", hex: "#FEC0DF", family: "solid" },
  { code: "E3", name: "E3", hex: "#FFB7E7", family: "solid" },
  { code: "E4", name: "E4", hex: "#E8649E", family: "solid" },
  { code: "E5", name: "E5", hex: "#F551A2", family: "solid" },
  { code: "E6", name: "E6", hex: "#F13D74", family: "solid" },
  { code: "E7", name: "E7", hex: "#C63478", family: "solid" },
  { code: "E8", name: "E8", hex: "#FFDBE9", family: "solid" },
  { code: "E9", name: "E9", hex: "#E970CC", family: "solid" },
  { code: "E10", name: "E10", hex: "#D33793", family: "solid" },
  { code: "E11", name: "E11", hex: "#FCDDD2", family: "solid" },
  { code: "E12", name: "E12", hex: "#F78FC3", family: "solid" },
  { code: "E13", name: "E13", hex: "#B5006D", family: "solid" },
  { code: "E14", name: "E14", hex: "#FFD1BA", family: "solid" },
  { code: "E15", name: "E15", hex: "#F8C7C9", family: "solid" },
  { code: "E16", name: "E16", hex: "#FFF3EB", family: "solid" },
  { code: "E17", name: "E17", hex: "#FFE2EA", family: "solid" },
  { code: "E18", name: "E18", hex: "#FFC7DB", family: "solid" },
  { code: "E19", name: "E19", hex: "#FEBAD5", family: "solid" },
  { code: "E20", name: "E20", hex: "#D8C7D1", family: "solid" },
  { code: "E21", name: "E21", hex: "#BD9DA1", family: "solid" },
  { code: "E22", name: "E22", hex: "#B785A1", family: "solid" },
  { code: "E23", name: "E23", hex: "#937A8D", family: "solid" },
  { code: "E24", name: "E24", hex: "#E1BCE8", family: "solid" },
  { code: "F1", name: "F1", hex: "#FD957B", family: "solid" },
  { code: "F2", name: "F2", hex: "#FC3D46", family: "solid" },
  { code: "F3", name: "F3", hex: "#F74941", family: "solid" },
  { code: "F4", name: "F4", hex: "#FC283C", family: "solid" },
  { code: "F5", name: "F5", hex: "#E7002F", family: "solid" },
  { code: "F6", name: "F6", hex: "#943630", family: "solid" },
  { code: "F7", name: "F7", hex: "#971937", family: "solid" },
  { code: "F8", name: "F8", hex: "#BC0028", family: "solid" },
  { code: "F9", name: "F9", hex: "#E2677A", family: "solid" },
  { code: "F10", name: "F10", hex: "#8A4526", family: "solid" },
  { code: "F11", name: "F11", hex: "#5A2121", family: "solid" },
  { code: "F12", name: "F12", hex: "#FD4E6A", family: "solid" },
  { code: "F13", name: "F13", hex: "#F35744", family: "solid" },
  { code: "F14", name: "F14", hex: "#FFA9AD", family: "solid" },
  { code: "F15", name: "F15", hex: "#D30022", family: "solid" },
  { code: "F16", name: "F16", hex: "#FEC2A6", family: "solid" },
  { code: "F17", name: "F17", hex: "#E69C79", family: "solid" },
  { code: "F18", name: "F18", hex: "#D37C46", family: "solid" },
  { code: "F19", name: "F19", hex: "#C1444A", family: "solid" },
  { code: "F20", name: "F20", hex: "#CD9391", family: "solid" },
  { code: "F21", name: "F21", hex: "#F7B4C6", family: "solid" },
  { code: "F22", name: "F22", hex: "#FDC0D0", family: "solid" },
  { code: "F23", name: "F23", hex: "#F67E66", family: "solid" },
  { code: "F24", name: "F24", hex: "#E698AA", family: "solid" },
  { code: "F25", name: "F25", hex: "#E54B4F", family: "solid" },
  { code: "G1", name: "G1", hex: "#FFE2CE", family: "solid" },
  { code: "G2", name: "G2", hex: "#FFC4AA", family: "solid" },
  { code: "G3", name: "G3", hex: "#F4C3A5", family: "solid" },
  { code: "G4", name: "G4", hex: "#E1B383", family: "solid" },
  { code: "G5", name: "G5", hex: "#EDB045", family: "solid" },
  { code: "G6", name: "G6", hex: "#E99C17", family: "solid" },
  { code: "G7", name: "G7", hex: "#9D5B3E", family: "solid" },
  { code: "G8", name: "G8", hex: "#753832", family: "solid" },
  { code: "G9", name: "G9", hex: "#E6B483", family: "solid" },
  { code: "G10", name: "G10", hex: "#D98C39", family: "solid" },
  { code: "G11", name: "G11", hex: "#E0C593", family: "solid" },
  { code: "G12", name: "G12", hex: "#FFC890", family: "solid" },
  { code: "G13", name: "G13", hex: "#B7714A", family: "solid" },
  { code: "G14", name: "G14", hex: "#8D614C", family: "solid" },
  { code: "G15", name: "G15", hex: "#FCF9E0", family: "solid" },
  { code: "G16", name: "G16", hex: "#F2D9BA", family: "solid" },
  { code: "G17", name: "G17", hex: "#78524B", family: "solid" },
  { code: "G18", name: "G18", hex: "#FFE4CC", family: "solid" },
  { code: "G19", name: "G19", hex: "#E07935", family: "solid" },
  { code: "G20", name: "G20", hex: "#A94023", family: "solid" },
  { code: "G21", name: "G21", hex: "#B88558", family: "solid" },
  { code: "H1", name: "H1", hex: "#FDFBFF", family: "solid" },
  { code: "H2", name: "H2", hex: "#FEFFFF", family: "solid" },
  { code: "H3", name: "H3", hex: "#B6B1BA", family: "solid" },
  { code: "H4", name: "H4", hex: "#89858C", family: "solid" },
  { code: "H5", name: "H5", hex: "#48464E", family: "solid" },
  { code: "H6", name: "H6", hex: "#2F2B2F", family: "solid" },
  { code: "H7", name: "H7", hex: "#000000", family: "solid" },
  { code: "H8", name: "H8", hex: "#E7D6DB", family: "solid" },
  { code: "H9", name: "H9", hex: "#EDEDED", family: "solid" },
  { code: "H10", name: "H10", hex: "#EEE9EA", family: "solid" },
  { code: "H11", name: "H11", hex: "#CECDD5", family: "solid" },
  { code: "H12", name: "H12", hex: "#FFF5ED", family: "solid" },
  { code: "H13", name: "H13", hex: "#F5ECD2", family: "solid" },
  { code: "H14", name: "H14", hex: "#CFD7D3", family: "solid" },
  { code: "H15", name: "H15", hex: "#98A6A8", family: "solid" },
  { code: "H16", name: "H16", hex: "#1D1414", family: "solid" },
  { code: "H17", name: "H17", hex: "#F1EDED", family: "solid" },
  { code: "H18", name: "H18", hex: "#FFFDF0", family: "solid" },
  { code: "H19", name: "H19", hex: "#F6EFE2", family: "solid" },
  { code: "H20", name: "H20", hex: "#949FA3", family: "solid" },
  { code: "H21", name: "H21", hex: "#FFFBE1", family: "solid" },
  { code: "H22", name: "H22", hex: "#CACAD4", family: "solid" },
  { code: "H23", name: "H23", hex: "#9A9D94", family: "solid" },
  { code: "M1", name: "M1", hex: "#BCC6B8", family: "solid" },
  { code: "M2", name: "M2", hex: "#8AA386", family: "solid" },
  { code: "M3", name: "M3", hex: "#697D80", family: "solid" },
  { code: "M4", name: "M4", hex: "#E3D2BC", family: "solid" },
  { code: "M5", name: "M5", hex: "#D0CCAA", family: "solid" },
  { code: "M6", name: "M6", hex: "#B0A782", family: "solid" },
  { code: "M7", name: "M7", hex: "#B4A497", family: "solid" },
  { code: "M8", name: "M8", hex: "#B38281", family: "solid" },
  { code: "M9", name: "M9", hex: "#A58767", family: "solid" },
  { code: "M10", name: "M10", hex: "#C5B2BC", family: "solid" },
  { code: "M11", name: "M11", hex: "#9F7594", family: "solid" },
  { code: "M12", name: "M12", hex: "#644749", family: "solid" },
  { code: "M13", name: "M13", hex: "#D19066", family: "solid" },
  { code: "M14", name: "M14", hex: "#C77362", family: "solid" },
  { code: "M15", name: "M15", hex: "#757D78", family: "solid" },
];

export const MARD291_COLORS: BeadColor[] = [
  { code: "A1", name: "A1", hex: "#FAF4C8", family: "solid" },
  { code: "A2", name: "A2", hex: "#FFFFD5", family: "solid" },
  { code: "A3", name: "A3", hex: "#FEFF8B", family: "solid" },
  { code: "A4", name: "A4", hex: "#FBED56", family: "solid" },
  { code: "A5", name: "A5", hex: "#F4D738", family: "solid" },
  { code: "A6", name: "A6", hex: "#FEAC4C", family: "solid" },
  { code: "A7", name: "A7", hex: "#FE8B4C", family: "solid" },
  { code: "A8", name: "A8", hex: "#FFDA45", family: "solid" },
  { code: "A9", name: "A9", hex: "#FF995B", family: "solid" },
  { code: "A10", name: "A10", hex: "#F77C31", family: "solid" },
  { code: "A11", name: "A11", hex: "#FFDD99", family: "solid" },
  { code: "A12", name: "A12", hex: "#FE9F72", family: "solid" },
  { code: "A13", name: "A13", hex: "#FFC365", family: "solid" },
  { code: "A14", name: "A14", hex: "#FD543D", family: "solid" },
  { code: "A15", name: "A15", hex: "#FFF365", family: "solid" },
  { code: "A16", name: "A16", hex: "#FFFF9F", family: "solid" },
  { code: "A17", name: "A17", hex: "#FFE36E", family: "solid" },
  { code: "A18", name: "A18", hex: "#FEBE7D", family: "solid" },
  { code: "A19", name: "A19", hex: "#FD7C72", family: "solid" },
  { code: "A20", name: "A20", hex: "#FFD568", family: "solid" },
  { code: "A21", name: "A21", hex: "#FFE395", family: "solid" },
  { code: "A22", name: "A22", hex: "#F4F57D", family: "solid" },
  { code: "A23", name: "A23", hex: "#E6C9B7", family: "solid" },
  { code: "A24", name: "A24", hex: "#F7F8A2", family: "solid" },
  { code: "A25", name: "A25", hex: "#FFD67D", family: "solid" },
  { code: "A26", name: "A26", hex: "#FFC830", family: "solid" },
  { code: "B1", name: "B1", hex: "#E6EE31", family: "solid" },
  { code: "B2", name: "B2", hex: "#63F347", family: "solid" },
  { code: "B3", name: "B3", hex: "#9EF780", family: "solid" },
  { code: "B4", name: "B4", hex: "#5DE035", family: "solid" },
  { code: "B5", name: "B5", hex: "#35E352", family: "solid" },
  { code: "B6", name: "B6", hex: "#65E2A6", family: "solid" },
  { code: "B7", name: "B7", hex: "#3DAF80", family: "solid" },
  { code: "B8", name: "B8", hex: "#1C9C4F", family: "solid" },
  { code: "B9", name: "B9", hex: "#27523A", family: "solid" },
  { code: "B10", name: "B10", hex: "#95D3C2", family: "solid" },
  { code: "B11", name: "B11", hex: "#5D722A", family: "solid" },
  { code: "B12", name: "B12", hex: "#166F41", family: "solid" },
  { code: "B13", name: "B13", hex: "#CAEB7B", family: "solid" },
  { code: "B14", name: "B14", hex: "#ADE946", family: "solid" },
  { code: "B15", name: "B15", hex: "#2E5132", family: "solid" },
  { code: "B16", name: "B16", hex: "#C5ED9C", family: "solid" },
  { code: "B17", name: "B17", hex: "#9BB13A", family: "solid" },
  { code: "B18", name: "B18", hex: "#E6EE49", family: "solid" },
  { code: "B19", name: "B19", hex: "#24B88C", family: "solid" },
  { code: "B20", name: "B20", hex: "#C2F0CC", family: "solid" },
  { code: "B21", name: "B21", hex: "#156A6B", family: "solid" },
  { code: "B22", name: "B22", hex: "#0B3C43", family: "solid" },
  { code: "B23", name: "B23", hex: "#303A21", family: "solid" },
  { code: "B24", name: "B24", hex: "#EEFCA5", family: "solid" },
  { code: "B25", name: "B25", hex: "#4E846D", family: "solid" },
  { code: "B26", name: "B26", hex: "#8D7A35", family: "solid" },
  { code: "B27", name: "B27", hex: "#CCE1AF", family: "solid" },
  { code: "B28", name: "B28", hex: "#9EE5B9", family: "solid" },
  { code: "B29", name: "B29", hex: "#C5E254", family: "solid" },
  { code: "B30", name: "B30", hex: "#E2FCB1", family: "solid" },
  { code: "B31", name: "B31", hex: "#B0E792", family: "solid" },
  { code: "B32", name: "B32", hex: "#9CAB5A", family: "solid" },
  { code: "C1", name: "C1", hex: "#E8FFE7", family: "solid" },
  { code: "C2", name: "C2", hex: "#A9F9FC", family: "solid" },
  { code: "C3", name: "C3", hex: "#A0E2FB", family: "solid" },
  { code: "C4", name: "C4", hex: "#41CCFF", family: "solid" },
  { code: "C5", name: "C5", hex: "#01ACEB", family: "solid" },
  { code: "C6", name: "C6", hex: "#50AAF0", family: "solid" },
  { code: "C7", name: "C7", hex: "#3677D2", family: "solid" },
  { code: "C8", name: "C8", hex: "#0F54C0", family: "solid" },
  { code: "C9", name: "C9", hex: "#324BCA", family: "solid" },
  { code: "C10", name: "C10", hex: "#3EBCE2", family: "solid" },
  { code: "C11", name: "C11", hex: "#28DDDE", family: "solid" },
  { code: "C12", name: "C12", hex: "#1C334D", family: "solid" },
  { code: "C13", name: "C13", hex: "#CDE8FF", family: "solid" },
  { code: "C14", name: "C14", hex: "#D5FDFF", family: "solid" },
  { code: "C15", name: "C15", hex: "#22C4C6", family: "solid" },
  { code: "C16", name: "C16", hex: "#1557A8", family: "solid" },
  { code: "C17", name: "C17", hex: "#04D1F6", family: "solid" },
  { code: "C18", name: "C18", hex: "#1D3344", family: "solid" },
  { code: "C19", name: "C19", hex: "#1887A2", family: "solid" },
  { code: "C20", name: "C20", hex: "#176DAF", family: "solid" },
  { code: "C21", name: "C21", hex: "#BEDDFF", family: "solid" },
  { code: "C22", name: "C22", hex: "#67B4BE", family: "solid" },
  { code: "C23", name: "C23", hex: "#C8E2FF", family: "solid" },
  { code: "C24", name: "C24", hex: "#7CC4FF", family: "solid" },
  { code: "C25", name: "C25", hex: "#A9E5E5", family: "solid" },
  { code: "C26", name: "C26", hex: "#3CAED8", family: "solid" },
  { code: "C27", name: "C27", hex: "#D3DFFA", family: "solid" },
  { code: "C28", name: "C28", hex: "#BBCFED", family: "solid" },
  { code: "C29", name: "C29", hex: "#34488E", family: "solid" },
  { code: "D1", name: "D1", hex: "#AEB4F2", family: "solid" },
  { code: "D2", name: "D2", hex: "#858EDD", family: "solid" },
  { code: "D3", name: "D3", hex: "#2F54AF", family: "solid" },
  { code: "D4", name: "D4", hex: "#182A84", family: "solid" },
  { code: "D5", name: "D5", hex: "#B843C5", family: "solid" },
  { code: "D6", name: "D6", hex: "#AC7BDE", family: "solid" },
  { code: "D7", name: "D7", hex: "#8854B3", family: "solid" },
  { code: "D8", name: "D8", hex: "#E2D3FF", family: "solid" },
  { code: "D9", name: "D9", hex: "#D5B9F8", family: "solid" },
  { code: "D10", name: "D10", hex: "#361851", family: "solid" },
  { code: "D11", name: "D11", hex: "#B9BAE1", family: "solid" },
  { code: "D12", name: "D12", hex: "#DE9AD4", family: "solid" },
  { code: "D13", name: "D13", hex: "#B90095", family: "solid" },
  { code: "D14", name: "D14", hex: "#8B279B", family: "solid" },
  { code: "D15", name: "D15", hex: "#2F1F90", family: "solid" },
  { code: "D16", name: "D16", hex: "#E3E1EE", family: "solid" },
  { code: "D17", name: "D17", hex: "#C4D4F6", family: "solid" },
  { code: "D18", name: "D18", hex: "#A45EC7", family: "solid" },
  { code: "D19", name: "D19", hex: "#D8C3D7", family: "solid" },
  { code: "D20", name: "D20", hex: "#9C32B2", family: "solid" },
  { code: "D21", name: "D21", hex: "#9A009B", family: "solid" },
  { code: "D22", name: "D22", hex: "#333A95", family: "solid" },
  { code: "D23", name: "D23", hex: "#EBDAFC", family: "solid" },
  { code: "D24", name: "D24", hex: "#7786E5", family: "solid" },
  { code: "D25", name: "D25", hex: "#494FC7", family: "solid" },
  { code: "D26", name: "D26", hex: "#DFC2F8", family: "solid" },
  { code: "E1", name: "E1", hex: "#FDD3CC", family: "solid" },
  { code: "E2", name: "E2", hex: "#FEC0DF", family: "solid" },
  { code: "E3", name: "E3", hex: "#FFB7E7", family: "solid" },
  { code: "E4", name: "E4", hex: "#E8649E", family: "solid" },
  { code: "E5", name: "E5", hex: "#F551A2", family: "solid" },
  { code: "E6", name: "E6", hex: "#F13D74", family: "solid" },
  { code: "E7", name: "E7", hex: "#C63478", family: "solid" },
  { code: "E8", name: "E8", hex: "#FFDBE9", family: "solid" },
  { code: "E9", name: "E9", hex: "#E970CC", family: "solid" },
  { code: "E10", name: "E10", hex: "#D33793", family: "solid" },
  { code: "E11", name: "E11", hex: "#FCDDD2", family: "solid" },
  { code: "E12", name: "E12", hex: "#F78FC3", family: "solid" },
  { code: "E13", name: "E13", hex: "#B5006D", family: "solid" },
  { code: "E14", name: "E14", hex: "#FFD1BA", family: "solid" },
  { code: "E15", name: "E15", hex: "#F8C7C9", family: "solid" },
  { code: "E16", name: "E16", hex: "#FFF3EB", family: "solid" },
  { code: "E17", name: "E17", hex: "#FFE2EA", family: "solid" },
  { code: "E18", name: "E18", hex: "#FFC7DB", family: "solid" },
  { code: "E19", name: "E19", hex: "#FEBAD5", family: "solid" },
  { code: "E20", name: "E20", hex: "#D8C7D1", family: "solid" },
  { code: "E21", name: "E21", hex: "#BD9DA1", family: "solid" },
  { code: "E22", name: "E22", hex: "#B785A1", family: "solid" },
  { code: "E23", name: "E23", hex: "#937A8D", family: "solid" },
  { code: "E24", name: "E24", hex: "#E1BCE8", family: "solid" },
  { code: "F1", name: "F1", hex: "#FD957B", family: "solid" },
  { code: "F2", name: "F2", hex: "#FC3D46", family: "solid" },
  { code: "F3", name: "F3", hex: "#F74941", family: "solid" },
  { code: "F4", name: "F4", hex: "#FC283C", family: "solid" },
  { code: "F5", name: "F5", hex: "#E7002F", family: "solid" },
  { code: "F6", name: "F6", hex: "#943630", family: "solid" },
  { code: "F7", name: "F7", hex: "#971937", family: "solid" },
  { code: "F8", name: "F8", hex: "#BC0028", family: "solid" },
  { code: "F9", name: "F9", hex: "#E2677A", family: "solid" },
  { code: "F10", name: "F10", hex: "#8A4526", family: "solid" },
  { code: "F11", name: "F11", hex: "#5A2121", family: "solid" },
  { code: "F12", name: "F12", hex: "#FD4E6A", family: "solid" },
  { code: "F13", name: "F13", hex: "#F35744", family: "solid" },
  { code: "F14", name: "F14", hex: "#FFA9AD", family: "solid" },
  { code: "F15", name: "F15", hex: "#D30022", family: "solid" },
  { code: "F16", name: "F16", hex: "#FEC2A6", family: "solid" },
  { code: "F17", name: "F17", hex: "#E69C79", family: "solid" },
  { code: "F18", name: "F18", hex: "#D37C46", family: "solid" },
  { code: "F19", name: "F19", hex: "#C1444A", family: "solid" },
  { code: "F20", name: "F20", hex: "#CD9391", family: "solid" },
  { code: "F21", name: "F21", hex: "#F7B4C6", family: "solid" },
  { code: "F22", name: "F22", hex: "#FDC0D0", family: "solid" },
  { code: "F23", name: "F23", hex: "#F67E66", family: "solid" },
  { code: "F24", name: "F24", hex: "#E698AA", family: "solid" },
  { code: "F25", name: "F25", hex: "#E54B4F", family: "solid" },
  { code: "G1", name: "G1", hex: "#FFE2CE", family: "solid" },
  { code: "G2", name: "G2", hex: "#FFC4AA", family: "solid" },
  { code: "G3", name: "G3", hex: "#F4C3A5", family: "solid" },
  { code: "G4", name: "G4", hex: "#E1B383", family: "solid" },
  { code: "G5", name: "G5", hex: "#EDB045", family: "solid" },
  { code: "G6", name: "G6", hex: "#E99C17", family: "solid" },
  { code: "G7", name: "G7", hex: "#9D5B3E", family: "solid" },
  { code: "G8", name: "G8", hex: "#753832", family: "solid" },
  { code: "G9", name: "G9", hex: "#E6B483", family: "solid" },
  { code: "G10", name: "G10", hex: "#D98C39", family: "solid" },
  { code: "G11", name: "G11", hex: "#E0C593", family: "solid" },
  { code: "G12", name: "G12", hex: "#FFC890", family: "solid" },
  { code: "G13", name: "G13", hex: "#B7714A", family: "solid" },
  { code: "G14", name: "G14", hex: "#8D614C", family: "solid" },
  { code: "G15", name: "G15", hex: "#FCF9E0", family: "solid" },
  { code: "G16", name: "G16", hex: "#F2D9BA", family: "solid" },
  { code: "G17", name: "G17", hex: "#78524B", family: "solid" },
  { code: "G18", name: "G18", hex: "#FFE4CC", family: "solid" },
  { code: "G19", name: "G19", hex: "#E07935", family: "solid" },
  { code: "G20", name: "G20", hex: "#A94023", family: "solid" },
  { code: "G21", name: "G21", hex: "#B88558", family: "solid" },
  { code: "H1", name: "H1", hex: "#FDFBFF", family: "solid" },
  { code: "H2", name: "H2", hex: "#FEFFFF", family: "solid" },
  { code: "H3", name: "H3", hex: "#B6B1BA", family: "solid" },
  { code: "H4", name: "H4", hex: "#89858C", family: "solid" },
  { code: "H5", name: "H5", hex: "#48464E", family: "solid" },
  { code: "H6", name: "H6", hex: "#2F2B2F", family: "solid" },
  { code: "H7", name: "H7", hex: "#000000", family: "solid" },
  { code: "H8", name: "H8", hex: "#E7D6DB", family: "solid" },
  { code: "H9", name: "H9", hex: "#EDEDED", family: "solid" },
  { code: "H10", name: "H10", hex: "#EEE9EA", family: "solid" },
  { code: "H11", name: "H11", hex: "#CECDD5", family: "solid" },
  { code: "H12", name: "H12", hex: "#FFF5ED", family: "solid" },
  { code: "H13", name: "H13", hex: "#F5ECD2", family: "solid" },
  { code: "H14", name: "H14", hex: "#CFD7D3", family: "solid" },
  { code: "H15", name: "H15", hex: "#98A6A8", family: "solid" },
  { code: "H16", name: "H16", hex: "#1D1414", family: "solid" },
  { code: "H17", name: "H17", hex: "#F1EDED", family: "solid" },
  { code: "H18", name: "H18", hex: "#FFFDF0", family: "solid" },
  { code: "H19", name: "H19", hex: "#F6EFE2", family: "solid" },
  { code: "H20", name: "H20", hex: "#949FA3", family: "solid" },
  { code: "H21", name: "H21", hex: "#FFFBE1", family: "solid" },
  { code: "H22", name: "H22", hex: "#CACAD4", family: "solid" },
  { code: "H23", name: "H23", hex: "#9A9D94", family: "solid" },
  { code: "M1", name: "M1", hex: "#BCC6B8", family: "solid" },
  { code: "M2", name: "M2", hex: "#8AA386", family: "solid" },
  { code: "M3", name: "M3", hex: "#697D80", family: "solid" },
  { code: "M4", name: "M4", hex: "#E3D2BC", family: "solid" },
  { code: "M5", name: "M5", hex: "#D0CCAA", family: "solid" },
  { code: "M6", name: "M6", hex: "#B0A782", family: "solid" },
  { code: "M7", name: "M7", hex: "#B4A497", family: "solid" },
  { code: "M8", name: "M8", hex: "#B38281", family: "solid" },
  { code: "M9", name: "M9", hex: "#A58767", family: "solid" },
  { code: "M10", name: "M10", hex: "#C5B2BC", family: "solid" },
  { code: "M11", name: "M11", hex: "#9F7594", family: "solid" },
  { code: "M12", name: "M12", hex: "#644749", family: "solid" },
  { code: "M13", name: "M13", hex: "#D19066", family: "solid" },
  { code: "M14", name: "M14", hex: "#C77362", family: "solid" },
  { code: "M15", name: "M15", hex: "#757D78", family: "solid" },
  { code: "P1", name: "P1", hex: "#FCF7F8", family: "solid" },
  { code: "P2", name: "P2", hex: "#B0A9AC", family: "solid" },
  { code: "P3", name: "P3", hex: "#AFDCAB", family: "solid" },
  { code: "P4", name: "P4", hex: "#FEA49F", family: "solid" },
  { code: "P5", name: "P5", hex: "#EE8C3E", family: "solid" },
  { code: "P6", name: "P6", hex: "#5FD0A7", family: "solid" },
  { code: "P7", name: "P7", hex: "#EB9270", family: "solid" },
  { code: "P8", name: "P8", hex: "#F0D958", family: "solid" },
  { code: "P9", name: "P9", hex: "#D9D9D9", family: "solid" },
  { code: "P10", name: "P10", hex: "#D9C7EA", family: "solid" },
  { code: "P11", name: "P11", hex: "#F3ECC9", family: "solid" },
  { code: "P12", name: "P12", hex: "#E6EEF2", family: "solid" },
  { code: "P13", name: "P13", hex: "#AACBEF", family: "solid" },
  { code: "P14", name: "P14", hex: "#337680", family: "solid" },
  { code: "P15", name: "P15", hex: "#668575", family: "solid" },
  { code: "P16", name: "P16", hex: "#FEBF45", family: "solid" },
  { code: "P17", name: "P17", hex: "#FEA324", family: "solid" },
  { code: "P18", name: "P18", hex: "#FEB89F", family: "solid" },
  { code: "P19", name: "P19", hex: "#FFFEEC", family: "solid" },
  { code: "P20", name: "P20", hex: "#FEBECF", family: "solid" },
  { code: "P21", name: "P21", hex: "#ECBEBF", family: "solid" },
  { code: "P22", name: "P22", hex: "#E4A89F", family: "solid" },
  { code: "P23", name: "P23", hex: "#A56268", family: "solid" },
  { code: "Q1", name: "Q1", hex: "#F2A5E8", family: "solid" },
  { code: "Q2", name: "Q2", hex: "#E9EC91", family: "solid" },
  { code: "Q3", name: "Q3", hex: "#FFFF00", family: "solid" },
  { code: "Q4", name: "Q4", hex: "#FFEBFA", family: "solid" },
  { code: "Q5", name: "Q5", hex: "#76CEDE", family: "solid" },
  { code: "R1", name: "R1", hex: "#D50D21", family: "solid" },
  { code: "R2", name: "R2", hex: "#F92F83", family: "solid" },
  { code: "R3", name: "R3", hex: "#FD8324", family: "solid" },
  { code: "R4", name: "R4", hex: "#F8EC31", family: "solid" },
  { code: "R5", name: "R5", hex: "#35C75B", family: "solid" },
  { code: "R6", name: "R6", hex: "#238891", family: "solid" },
  { code: "R7", name: "R7", hex: "#19779D", family: "solid" },
  { code: "R8", name: "R8", hex: "#1A60C3", family: "solid" },
  { code: "R9", name: "R9", hex: "#9A56B4", family: "solid" },
  { code: "R10", name: "R10", hex: "#FFDB4C", family: "solid" },
  { code: "R11", name: "R11", hex: "#FFEBFA", family: "solid" },
  { code: "R12", name: "R12", hex: "#D8D5CE", family: "solid" },
  { code: "R13", name: "R13", hex: "#55514C", family: "solid" },
  { code: "R14", name: "R14", hex: "#9FE4DF", family: "solid" },
  { code: "R15", name: "R15", hex: "#77CEE9", family: "solid" },
  { code: "R16", name: "R16", hex: "#3ECFCA", family: "solid" },
  { code: "R17", name: "R17", hex: "#4A867A", family: "solid" },
  { code: "R18", name: "R18", hex: "#7FCD9D", family: "solid" },
  { code: "R19", name: "R19", hex: "#CDE55D", family: "solid" },
  { code: "R20", name: "R20", hex: "#E8C7B4", family: "solid" },
  { code: "R21", name: "R21", hex: "#AD6F3C", family: "solid" },
  { code: "R22", name: "R22", hex: "#6C372F", family: "solid" },
  { code: "R23", name: "R23", hex: "#FEB872", family: "solid" },
  { code: "R24", name: "R24", hex: "#F3C1C0", family: "solid" },
  { code: "R25", name: "R25", hex: "#C9675E", family: "solid" },
  { code: "R26", name: "R26", hex: "#D293BE", family: "solid" },
  { code: "R27", name: "R27", hex: "#EA8CB1", family: "solid" },
  { code: "R28", name: "R28", hex: "#9C87D6", family: "solid" },
  { code: "T1", name: "T1", hex: "#FFFFFF", family: "solid" },
  { code: "Y1", name: "Y1", hex: "#FD6FB4", family: "solid" },
  { code: "Y2", name: "Y2", hex: "#FEB481", family: "solid" },
  { code: "Y3", name: "Y3", hex: "#D7FAA0", family: "solid" },
  { code: "Y4", name: "Y4", hex: "#8BDBFA", family: "solid" },
  { code: "Y5", name: "Y5", hex: "#E987EA", family: "solid" },
  { code: "ZG1", name: "ZG1", hex: "#DAABB3", family: "solid" },
  { code: "ZG2", name: "ZG2", hex: "#D6AA87", family: "solid" },
  { code: "ZG3", name: "ZG3", hex: "#C1BD8D", family: "solid" },
  { code: "ZG4", name: "ZG4", hex: "#96869F", family: "solid" },
  { code: "ZG5", name: "ZG5", hex: "#8490A6", family: "solid" },
  { code: "ZG6", name: "ZG6", hex: "#94BFE2", family: "solid" },
  { code: "ZG7", name: "ZG7", hex: "#E2A9D2", family: "solid" },
  { code: "ZG8", name: "ZG8", hex: "#AB91C0", family: "solid" },
];

export const COCO291_COLORS: BeadColor[] = [
  { code: "A01", name: "A01", hex: "#FEFFFF", family: "solid" },
  { code: "A02", name: "A02", hex: "#FDFBFF", family: "solid" },
  { code: "A03", name: "A03", hex: "#FFFDF0", family: "solid" },
  { code: "A04", name: "A04", hex: "#FFF5ED", family: "solid" },
  { code: "A05", name: "A05", hex: "#F6EFE2", family: "solid" },
  { code: "A06", name: "A06", hex: "#F5ECD2", family: "solid" },
  { code: "A07", name: "A07", hex: "#F1EDED", family: "solid" },
  { code: "A08", name: "A08", hex: "#EDEDED", family: "solid" },
  { code: "A09", name: "A09", hex: "#E7D6DB", family: "solid" },
  { code: "A10", name: "A10", hex: "#EEE9EA", family: "solid" },
  { code: "A11", name: "A11", hex: "#FFFBE1", family: "solid" },
  { code: "A12", name: "A12", hex: "#CACAD4", family: "solid" },
  { code: "B01", name: "B01", hex: "#CECDD5", family: "solid" },
  { code: "B02", name: "B02", hex: "#CFD7D3", family: "solid" },
  { code: "B03", name: "B03", hex: "#B6B1BA", family: "solid" },
  { code: "B04", name: "B04", hex: "#98A6A8", family: "solid" },
  { code: "B05", name: "B05", hex: "#89858C", family: "solid" },
  { code: "B06", name: "B06", hex: "#48464E", family: "solid" },
  { code: "B07", name: "B07", hex: "#2F2B2F", family: "solid" },
  { code: "B08", name: "B08", hex: "#1D1414", family: "solid" },
  { code: "B09", name: "B09", hex: "#000000", family: "solid" },
  { code: "B10", name: "B10", hex: "#949FA3", family: "solid" },
  { code: "B11", name: "B11", hex: "#9A9D94", family: "solid" },
  { code: "C01", name: "C01", hex: "#FD4E6A", family: "solid" },
  { code: "C02", name: "C02", hex: "#FC3D46", family: "solid" },
  { code: "C03", name: "C03", hex: "#F74941", family: "solid" },
  { code: "C04", name: "C04", hex: "#F35744", family: "solid" },
  { code: "C05", name: "C05", hex: "#FD543D", family: "solid" },
  { code: "C06", name: "C06", hex: "#FC283C", family: "solid" },
  { code: "C07", name: "C07", hex: "#E7002F", family: "solid" },
  { code: "C08", name: "C08", hex: "#D30022", family: "solid" },
  { code: "C09", name: "C09", hex: "#BC0028", family: "solid" },
  { code: "C10", name: "C10", hex: "#971937", family: "solid" },
  { code: "D01", name: "D01", hex: "#FFDD99", family: "solid" },
  { code: "D02", name: "D02", hex: "#FEBE7D", family: "solid" },
  { code: "D03", name: "D03", hex: "#F4D738", family: "solid" },
  { code: "D04", name: "D04", hex: "#FFC365", family: "solid" },
  { code: "D05", name: "D05", hex: "#FEAC4C", family: "solid" },
  { code: "D06", name: "D06", hex: "#FF995B", family: "solid" },
  { code: "D07", name: "D07", hex: "#F77C31", family: "solid" },
  { code: "D08", name: "D08", hex: "#FE8B4C", family: "solid" },
  { code: "E01", name: "E01", hex: "#FFFFD5", family: "solid" },
  { code: "E02", name: "E02", hex: "#FAF4C8", family: "solid" },
  { code: "E03", name: "E03", hex: "#FFFF9F", family: "solid" },
  { code: "E04", name: "E04", hex: "#FFF365", family: "solid" },
  { code: "E05", name: "E05", hex: "#FEFF8B", family: "solid" },
  { code: "E06", name: "E06", hex: "#FFE36E", family: "solid" },
  { code: "E07", name: "E07", hex: "#FBED56", family: "solid" },
  { code: "E08", name: "E08", hex: "#FFDA45", family: "solid" },
  { code: "E09", name: "E09", hex: "#FFD568", family: "solid" },
  { code: "E10", name: "E10", hex: "#FFE395", family: "solid" },
  { code: "E11", name: "E11", hex: "#F4F57D", family: "solid" },
  { code: "E12", name: "E12", hex: "#E6C9B7", family: "solid" },
  { code: "E13", name: "E13", hex: "#F7F8A2", family: "solid" },
  { code: "E14", name: "E14", hex: "#FFD67D", family: "solid" },
  { code: "E15", name: "E15", hex: "#FFC830", family: "solid" },
  { code: "F01", name: "F01", hex: "#EEFCA5", family: "solid" },
  { code: "F02", name: "F02", hex: "#CAEB7B", family: "solid" },
  { code: "F03", name: "F03", hex: "#C5ED9C", family: "solid" },
  { code: "F04", name: "F04", hex: "#9EF780", family: "solid" },
  { code: "F05", name: "F05", hex: "#E6EE31", family: "solid" },
  { code: "F06", name: "F06", hex: "#ADE946", family: "solid" },
  { code: "F07", name: "F07", hex: "#E6EE49", family: "solid" },
  { code: "F08", name: "F08", hex: "#63F347", family: "solid" },
  { code: "F09", name: "F09", hex: "#5DE035", family: "solid" },
  { code: "F10", name: "F10", hex: "#35E352", family: "solid" },
  { code: "F11", name: "F11", hex: "#1C9C4F", family: "solid" },
  { code: "F12", name: "F12", hex: "#166F41", family: "solid" },
  { code: "F13", name: "F13", hex: "#9BB13A", family: "solid" },
  { code: "F14", name: "F14", hex: "#5D722A", family: "solid" },
  { code: "F15", name: "F15", hex: "#2E5132", family: "solid" },
  { code: "F16", name: "F16", hex: "#27523A", family: "solid" },
  { code: "F17", name: "F17", hex: "#303A21", family: "solid" },
  { code: "F18", name: "F18", hex: "#4E846D", family: "solid" },
  { code: "F19", name: "F19", hex: "#8D7A35", family: "solid" },
  { code: "F20", name: "F20", hex: "#CCE1AF", family: "solid" },
  { code: "F21", name: "F21", hex: "#9EE5B9", family: "solid" },
  { code: "F22", name: "F22", hex: "#C5E254", family: "solid" },
  { code: "F23", name: "F23", hex: "#E2FCB1", family: "solid" },
  { code: "F24", name: "F24", hex: "#B0E792", family: "solid" },
  { code: "F25", name: "F25", hex: "#9CAB5A", family: "solid" },
  { code: "G01", name: "G01", hex: "#E8FFE7", family: "solid" },
  { code: "G02", name: "G02", hex: "#C2F0CC", family: "solid" },
  { code: "G03", name: "G03", hex: "#95D3C2", family: "solid" },
  { code: "G04", name: "G04", hex: "#65E2A6", family: "solid" },
  { code: "G05", name: "G05", hex: "#3DAF80", family: "solid" },
  { code: "G06", name: "G06", hex: "#24B88C", family: "solid" },
  { code: "G07", name: "G07", hex: "#156A6B", family: "solid" },
  { code: "G08", name: "G08", hex: "#0B3C43", family: "solid" },
  { code: "GB1", name: "GB1", hex: "#DAABB3", family: "solid" },
  { code: "GB2", name: "GB2", hex: "#D6AA87", family: "solid" },
  { code: "GB3", name: "GB3", hex: "#C1BD8D", family: "solid" },
  { code: "GB4", name: "GB4", hex: "#96869F", family: "solid" },
  { code: "GB5", name: "GB5", hex: "#8490A6", family: "solid" },
  { code: "GB6", name: "GB6", hex: "#94BFE2", family: "solid" },
  { code: "GB7", name: "GB7", hex: "#E2A9D2", family: "solid" },
  { code: "GB8", name: "GB8", hex: "#AB91C0", family: "solid" },
  { code: "H01", name: "H01", hex: "#CDE8FF", family: "solid" },
  { code: "H02", name: "H02", hex: "#D5FDFF", family: "solid" },
  { code: "H03", name: "H03", hex: "#A9F9FC", family: "solid" },
  { code: "H04", name: "H04", hex: "#A0E2FB", family: "solid" },
  { code: "H05", name: "H05", hex: "#41CCFF", family: "solid" },
  { code: "H06", name: "H06", hex: "#BEDDFF", family: "solid" },
  { code: "H07", name: "H07", hex: "#01ACEB", family: "solid" },
  { code: "H08", name: "H08", hex: "#50AAF0", family: "solid" },
  { code: "H09", name: "H09", hex: "#3EBCE2", family: "solid" },
  { code: "H10", name: "H10", hex: "#28DDDE", family: "solid" },
  { code: "H11", name: "H11", hex: "#22C4C6", family: "solid" },
  { code: "H12", name: "H12", hex: "#1887A2", family: "solid" },
  { code: "H13", name: "H13", hex: "#3677D2", family: "solid" },
  { code: "H14", name: "H14", hex: "#0F54C0", family: "solid" },
  { code: "H15", name: "H15", hex: "#2F54AF", family: "solid" },
  { code: "H16", name: "H16", hex: "#324BCA", family: "solid" },
  { code: "H17", name: "H17", hex: "#176DAF", family: "solid" },
  { code: "H18", name: "H18", hex: "#1557A8", family: "solid" },
  { code: "H19", name: "H19", hex: "#04D1F6", family: "solid" },
  { code: "H20", name: "H20", hex: "#182A84", family: "solid" },
  { code: "H21", name: "H21", hex: "#333A95", family: "solid" },
  { code: "H22", name: "H22", hex: "#2F1F90", family: "solid" },
  { code: "H23", name: "H23", hex: "#1C334D", family: "solid" },
  { code: "H24", name: "H24", hex: "#1D3344", family: "solid" },
  { code: "H25", name: "H25", hex: "#67B4BE", family: "solid" },
  { code: "H26", name: "H26", hex: "#C8E2FF", family: "solid" },
  { code: "H27", name: "H27", hex: "#7CC4FF", family: "solid" },
  { code: "H28", name: "H28", hex: "#A9E5E5", family: "solid" },
  { code: "H29", name: "H29", hex: "#3CAED8", family: "solid" },
  { code: "H30", name: "H30", hex: "#D3DFFA", family: "solid" },
  { code: "H31", name: "H31", hex: "#BBCFED", family: "solid" },
  { code: "H32", name: "H32", hex: "#34488E", family: "solid" },
  { code: "J01", name: "J01", hex: "#E3E1EE", family: "solid" },
  { code: "J02", name: "J02", hex: "#EBDAFC", family: "solid" },
  { code: "J03", name: "J03", hex: "#E2D3FF", family: "solid" },
  { code: "J04", name: "J04", hex: "#D5B9F8", family: "solid" },
  { code: "J05", name: "J05", hex: "#C4D4F6", family: "solid" },
  { code: "J06", name: "J06", hex: "#B9BAE1", family: "solid" },
  { code: "J07", name: "J07", hex: "#AEB4F2", family: "solid" },
  { code: "J08", name: "J08", hex: "#858EDD", family: "solid" },
  { code: "J09", name: "J09", hex: "#D8C3D7", family: "solid" },
  { code: "J10", name: "J10", hex: "#DE9AD4", family: "solid" },
  { code: "J11", name: "J11", hex: "#AC7BDE", family: "solid" },
  { code: "J12", name: "J12", hex: "#B843C5", family: "solid" },
  { code: "J13", name: "J13", hex: "#A45EC7", family: "solid" },
  { code: "J14", name: "J14", hex: "#B90095", family: "solid" },
  { code: "J15", name: "J15", hex: "#8854B3", family: "solid" },
  { code: "J16", name: "J16", hex: "#8B279B", family: "solid" },
  { code: "J17", name: "J17", hex: "#9C32B2", family: "solid" },
  { code: "J18", name: "J18", hex: "#9A009B", family: "solid" },
  { code: "J19", name: "J19", hex: "#361851", family: "solid" },
  { code: "J20", name: "J20", hex: "#7786E5", family: "solid" },
  { code: "J21", name: "J21", hex: "#494FC7", family: "solid" },
  { code: "J22", name: "J22", hex: "#DFC2F8", family: "solid" },
  { code: "K01", name: "K01", hex: "#FFF3EB", family: "solid" },
  { code: "K02", name: "K02", hex: "#FCDDD2", family: "solid" },
  { code: "K03", name: "K03", hex: "#FDD3CC", family: "solid" },
  { code: "K04", name: "K04", hex: "#F8C7C9", family: "solid" },
  { code: "K05", name: "K05", hex: "#FFD1BA", family: "solid" },
  { code: "K06", name: "K06", hex: "#FEC2A6", family: "solid" },
  { code: "K07", name: "K07", hex: "#FFA9AD", family: "solid" },
  { code: "K08", name: "K08", hex: "#FD957B", family: "solid" },
  { code: "K09", name: "K09", hex: "#FE9F72", family: "solid" },
  { code: "K10", name: "K10", hex: "#FD7C72", family: "solid" },
  { code: "K11", name: "K11", hex: "#FFE2EA", family: "solid" },
  { code: "K12", name: "K12", hex: "#FFDBE9", family: "solid" },
  { code: "K13", name: "K13", hex: "#FFC7DB", family: "solid" },
  { code: "K14", name: "K14", hex: "#FEBAD5", family: "solid" },
  { code: "K15", name: "K15", hex: "#FEC0DF", family: "solid" },
  { code: "K16", name: "K16", hex: "#F78FC3", family: "solid" },
  { code: "K17", name: "K17", hex: "#FFB7E7", family: "solid" },
  { code: "K18", name: "K18", hex: "#E970CC", family: "solid" },
  { code: "K19", name: "K19", hex: "#F551A2", family: "solid" },
  { code: "K20", name: "K20", hex: "#E2677A", family: "solid" },
  { code: "K21", name: "K21", hex: "#E8649E", family: "solid" },
  { code: "K22", name: "K22", hex: "#F13D74", family: "solid" },
  { code: "K23", name: "K23", hex: "#D33793", family: "solid" },
  { code: "K24", name: "K24", hex: "#B5006D", family: "solid" },
  { code: "K25", name: "K25", hex: "#C63478", family: "solid" },
  { code: "K26", name: "K26", hex: "#D8C7D1", family: "solid" },
  { code: "K27", name: "K27", hex: "#BD9DA1", family: "solid" },
  { code: "K28", name: "K28", hex: "#B785A1", family: "solid" },
  { code: "K29", name: "K29", hex: "#937A8D", family: "solid" },
  { code: "K30", name: "K30", hex: "#E1BCE8", family: "solid" },
  { code: "K31", name: "K31", hex: "#E69C79", family: "solid" },
  { code: "K32", name: "K32", hex: "#D37C46", family: "solid" },
  { code: "K33", name: "K33", hex: "#C1444A", family: "solid" },
  { code: "K34", name: "K34", hex: "#CD9391", family: "solid" },
  { code: "K35", name: "K35", hex: "#F7B4C6", family: "solid" },
  { code: "K36", name: "K36", hex: "#FDC0D0", family: "solid" },
  { code: "K37", name: "K37", hex: "#F67E66", family: "solid" },
  { code: "K38", name: "K38", hex: "#E698AA", family: "solid" },
  { code: "K39", name: "K39", hex: "#E54B4F", family: "solid" },
  { code: "L01", name: "L01", hex: "#D50D21", family: "solid" },
  { code: "L02", name: "L02", hex: "#F92F83", family: "solid" },
  { code: "L03", name: "L03", hex: "#FD8324", family: "solid" },
  { code: "L04", name: "L04", hex: "#F8EC31", family: "solid" },
  { code: "L05", name: "L05", hex: "#35C75B", family: "solid" },
  { code: "L06", name: "L06", hex: "#238891", family: "solid" },
  { code: "L07", name: "L07", hex: "#19779D", family: "solid" },
  { code: "L08", name: "L08", hex: "#1A60C3", family: "solid" },
  { code: "L09", name: "L09", hex: "#9A56B4", family: "solid" },
  { code: "L10", name: "L10", hex: "#FFDB4C", family: "solid" },
  { code: "L11", name: "L11", hex: "#FFEBFB", family: "solid" },
  { code: "L12", name: "L12", hex: "#D8D5CE", family: "solid" },
  { code: "L13", name: "L13", hex: "#55514C", family: "solid" },
  { code: "L14", name: "L14", hex: "#FFFFFF", family: "solid" },
  { code: "M01", name: "M01", hex: "#FCF7F8", family: "solid" },
  { code: "M02", name: "M02", hex: "#B0A9AC", family: "solid" },
  { code: "M03", name: "M03", hex: "#AFDCAB", family: "solid" },
  { code: "M04", name: "M04", hex: "#FEA49F", family: "solid" },
  { code: "M05", name: "M05", hex: "#EE8C3E", family: "solid" },
  { code: "M06", name: "M06", hex: "#5FD0A7", family: "solid" },
  { code: "M07", name: "M07", hex: "#EB9270", family: "solid" },
  { code: "M08", name: "M08", hex: "#F0D958", family: "solid" },
  { code: "M09", name: "M09", hex: "#D9D9D9", family: "solid" },
  { code: "M10", name: "M10", hex: "#D9C7EA", family: "solid" },
  { code: "M11", name: "M11", hex: "#F3ECC9", family: "solid" },
  { code: "M12", name: "M12", hex: "#E6EEF2", family: "solid" },
  { code: "M13", name: "M13", hex: "#AACBEF", family: "solid" },
  { code: "M14", name: "M14", hex: "#337680", family: "solid" },
  { code: "M15", name: "M15", hex: "#668575", family: "solid" },
  { code: "M16", name: "M16", hex: "#FEBF45", family: "solid" },
  { code: "M17", name: "M17", hex: "#FEA324", family: "solid" },
  { code: "M18", name: "M18", hex: "#FEB89F", family: "solid" },
  { code: "M19", name: "M19", hex: "#FFFEEC", family: "solid" },
  { code: "M20", name: "M20", hex: "#ECBEBF", family: "solid" },
  { code: "M21", name: "M21", hex: "#FEBECF", family: "solid" },
  { code: "M22", name: "M22", hex: "#E4A89F", family: "solid" },
  { code: "M23", name: "M23", hex: "#A56268", family: "solid" },
  { code: "N01", name: "N01", hex: "#FD6FB4", family: "solid" },
  { code: "N02", name: "N02", hex: "#FEB481", family: "solid" },
  { code: "N03", name: "N03", hex: "#D7FAA0", family: "solid" },
  { code: "N04", name: "N04", hex: "#8BDBFA", family: "solid" },
  { code: "N05", name: "N05", hex: "#E987EA", family: "solid" },
  { code: "S1", name: "S1", hex: "#9FE4DF", family: "solid" },
  { code: "S2", name: "S2", hex: "#77CEE9", family: "solid" },
  { code: "S3", name: "S3", hex: "#3ECFCA", family: "solid" },
  { code: "S4", name: "S4", hex: "#4A867A", family: "solid" },
  { code: "S5", name: "S5", hex: "#7FCD9D", family: "solid" },
  { code: "S6", name: "S6", hex: "#CDE55D", family: "solid" },
  { code: "S7", name: "S7", hex: "#E8C7B4", family: "solid" },
  { code: "S8", name: "S8", hex: "#AD6F3C", family: "solid" },
  { code: "S9", name: "S9", hex: "#6C372F", family: "solid" },
  { code: "S10", name: "S10", hex: "#FEB872", family: "solid" },
  { code: "S11", name: "S11", hex: "#F3C1C0", family: "solid" },
  { code: "S12", name: "S12", hex: "#C9675E", family: "solid" },
  { code: "S13", name: "S13", hex: "#D293BE", family: "solid" },
  { code: "S14", name: "S14", hex: "#EA8CB1", family: "solid" },
  { code: "S15", name: "S15", hex: "#9C87D6", family: "solid" },
  { code: "W1", name: "W1", hex: "#FFFF00", family: "solid" },
  { code: "W2", name: "W2", hex: "#FFEBFA", family: "solid" },
  { code: "W3", name: "W3", hex: "#F2A5E8", family: "solid" },
  { code: "W4", name: "W4", hex: "#E9EC91", family: "solid" },
  { code: "W5", name: "W5", hex: "#76CEDE", family: "solid" },
  { code: "Y01", name: "Y01", hex: "#BCC6B8", family: "solid" },
  { code: "Y02", name: "Y02", hex: "#8AA386", family: "solid" },
  { code: "Y03", name: "Y03", hex: "#697D80", family: "solid" },
  { code: "Y04", name: "Y04", hex: "#E3D2BC", family: "solid" },
  { code: "Y05", name: "Y05", hex: "#D0CCAA", family: "solid" },
  { code: "Y06", name: "Y06", hex: "#B0A782", family: "solid" },
  { code: "Y07", name: "Y07", hex: "#B4A497", family: "solid" },
  { code: "Y08", name: "Y08", hex: "#B38281", family: "solid" },
  { code: "Y09", name: "Y09", hex: "#A58767", family: "solid" },
  { code: "Y10", name: "Y10", hex: "#C5B2BC", family: "solid" },
  { code: "Y11", name: "Y11", hex: "#9F7594", family: "solid" },
  { code: "Y12", name: "Y12", hex: "#644749", family: "solid" },
  { code: "Y13", name: "Y13", hex: "#D19066", family: "solid" },
  { code: "Y14", name: "Y14", hex: "#C77362", family: "solid" },
  { code: "Y15", name: "Y15", hex: "#757D78", family: "solid" },
  { code: "Z01", name: "Z01", hex: "#FFE4CC", family: "solid" },
  { code: "Z02", name: "Z02", hex: "#FFE2CE", family: "solid" },
  { code: "Z03", name: "Z03", hex: "#FCF9E0", family: "solid" },
  { code: "Z04", name: "Z04", hex: "#F2D9BA", family: "solid" },
  { code: "Z05", name: "Z05", hex: "#FFC4AA", family: "solid" },
  { code: "Z06", name: "Z06", hex: "#F4C3A5", family: "solid" },
  { code: "Z07", name: "Z07", hex: "#E0C593", family: "solid" },
  { code: "Z08", name: "Z08", hex: "#E1B383", family: "solid" },
  { code: "Z09", name: "Z09", hex: "#E6B483", family: "solid" },
  { code: "Z10", name: "Z10", hex: "#EDB045", family: "solid" },
  { code: "Z11", name: "Z11", hex: "#E99C17", family: "solid" },
  { code: "Z12", name: "Z12", hex: "#E07935", family: "solid" },
  { code: "Z13", name: "Z13", hex: "#FFC890", family: "solid" },
  { code: "Z14", name: "Z14", hex: "#B7714A", family: "solid" },
  { code: "Z15", name: "Z15", hex: "#D98C39", family: "solid" },
  { code: "Z16", name: "Z16", hex: "#78524B", family: "solid" },
  { code: "Z17", name: "Z17", hex: "#8D614C", family: "solid" },
  { code: "Z18", name: "Z18", hex: "#9D5B3E", family: "solid" },
  { code: "Z19", name: "Z19", hex: "#A94023", family: "solid" },
  { code: "Z20", name: "Z20", hex: "#8A4526", family: "solid" },
  { code: "Z21", name: "Z21", hex: "#943630", family: "solid" },
  { code: "Z22", name: "Z22", hex: "#753832", family: "solid" },
  { code: "Z23", name: "Z23", hex: "#5A2121", family: "solid" },
  { code: "Z24", name: "Z24", hex: "#B88558", family: "solid" },
];

export const HAMA_COLORS: BeadColor[] = [
  { code: "H01", name: "White", hex: "#ECEDED", family: "solid" },
  { code: "H02", name: "Cream", hex: "#F0E8B9", family: "solid" },
  { code: "H03", name: "Gold", hex: "#F0B901", family: "solid" },
  { code: "H04", name: "Orange", hex: "#E64F27", family: "solid" },
  { code: "H05", name: "Red", hex: "#B63136", family: "solid" },
  { code: "H06", name: "Pink", hex: "#E1889F", family: "solid" },
  { code: "H07", name: "Purple", hex: "#694A82", family: "solid" },
  { code: "H08", name: "Dark Blue", hex: "#2C4690", family: "solid" },
  { code: "H09", name: "Blue", hex: "#305CB0", family: "solid" },
  { code: "H10", name: "Dark Green", hex: "#256847", family: "solid" },
  { code: "H11", name: "Teal", hex: "#49AE89", family: "solid" },
  { code: "H12", name: "Brown", hex: "#534137", family: "solid" },
  { code: "H13", name: "Transparent Red", hex: "#C02435", family: "translucent" },
  { code: "H14", name: "Transparent Yellow", hex: "#E4AA32", family: "translucent" },
  { code: "H15", name: "Transparent Blue", hex: "#487ED5", family: "translucent" },
  { code: "H16", name: "Transparent Green", hex: "#37B876", family: "translucent" },
  { code: "H17", name: "Gray", hex: "#83888A", family: "solid" },
  { code: "H18", name: "Black", hex: "#2E2F31", family: "solid" },
  { code: "H19", name: "Clear", hex: "#D8D2CE", family: "translucent" },
  { code: "H20", name: "Dark Brown", hex: "#7F332A", family: "solid" },
  { code: "H21", name: "Tan", hex: "#A5693F", family: "solid" },
  { code: "H22", name: "Burgundy", hex: "#A52D36", family: "solid" },
  { code: "H24", name: "Translucent Purple", hex: "#683E9A", family: "translucent" },
  { code: "H25", name: "Translucent Brown", hex: "#87593D", family: "translucent" },
  { code: "H26", name: "Salmon", hex: "#DE9B90", family: "solid" },
  { code: "H27", name: "Tan Light", hex: "#DEB48B", family: "solid" },
  { code: "H28", name: "Dark Gray", hex: "#363F38", family: "solid" },
  { code: "H29", name: "Magenta", hex: "#B9395E", family: "solid" },
  { code: "H30", name: "Maroon", hex: "#592F38", family: "solid" },
  { code: "H31", name: "Steel Blue", hex: "#6797AE", family: "solid" },
  { code: "H32", name: "Neon Fuchsia", hex: "#FF208D", family: "neon" },
  { code: "H33", name: "Bright Red", hex: "#FF3956", family: "solid" },
  { code: "H34", name: "Neon Yellow", hex: "#E5EF13", family: "neon" },
  { code: "H35", name: "Neon Red", hex: "#FF2833", family: "neon" },
  { code: "H36", name: "Neon Blue", hex: "#2353B0", family: "neon" },
  { code: "H37", name: "Neon Green", hex: "#06B73C", family: "neon" },
  { code: "H38", name: "Neon Orange", hex: "#FD8600", family: "neon" },
  { code: "H39", name: "Fluorescent Yellow", hex: "#F1F21C", family: "neon" },
  { code: "H40", name: "Fluorescent Orange", hex: "#FE630B", family: "neon" },
  { code: "H41", name: "Fluorescent Blue", hex: "#2659B2", family: "neon" },
  { code: "H42", name: "Fluorescent Green", hex: "#0CBD51", family: "neon" },
  { code: "H43", name: "Bright Yellow", hex: "#F0EA37", family: "solid" },
  { code: "H44", name: "Rose", hex: "#EE6972", family: "solid" },
  { code: "H45", name: "Mauve", hex: "#886DB9", family: "solid" },
  { code: "H46", name: "Cornflower Blue", hex: "#629ED7", family: "solid" },
  { code: "H47", name: "Green", hex: "#83CB70", family: "solid" },
  { code: "H48", name: "Orchid", hex: "#CF70B7", family: "solid" },
  { code: "H49", name: "Ocean Blue", hex: "#4998BC", family: "solid" },
  { code: "H60", name: "Burnt Orange", hex: "#F49422", family: "solid" },
  { code: "H61", name: "Gold Metallic", hex: "#D99350", family: "metallic" },
  { code: "H62", name: "Silver Metallic", hex: "#48474A", family: "metallic" },
  { code: "H63", name: "Bronze Metallic", hex: "#42312F", family: "metallic" },
  { code: "H64", name: "Pearl", hex: "#EFEBE4", family: "pearl" },
  { code: "H70", name: "Periwinkle", hex: "#B6B6D4", family: "solid" },
  { code: "H71", name: "Charcoal", hex: "#464541", family: "solid" },
  { code: "H72", name: "Translucent Pink", hex: "#F097B0", family: "translucent" },
  { code: "H73", name: "Translucent Aqua", hex: "#59AEF5", family: "translucent" },
  { code: "H74", name: "Translucent Lilac", hex: "#5B55BD", family: "translucent" },
  { code: "H75", name: "Caramel", hex: "#BF7B4D", family: "solid" },
  { code: "H76", name: "Chocolate", hex: "#663317", family: "solid" },
  { code: "H77", name: "Beige", hex: "#EDE7DF", family: "solid" },
  { code: "H78", name: "Light Orange", hex: "#FFC99A", family: "solid" },
  { code: "H79", name: "Apricot", hex: "#F08643", family: "solid" },
  { code: "H82", name: "Wine", hex: "#962F5C", family: "solid" },
  { code: "H83", name: "Teal Blue", hex: "#0178A4", family: "solid" },
  { code: "H84", name: "Olive", hex: "#8B924C", family: "solid" },
  { code: "H95", name: "Light Pink", hex: "#F8CCE0", family: "solid" },
  { code: "H96", name: "Lilac", hex: "#D4B1E3", family: "solid" },
  { code: "H97", name: "Light Blue", hex: "#A2D3FE", family: "solid" },
  { code: "H98", name: "Mint", hex: "#9ADBB1", family: "solid" },
  { code: "H101", name: "Light Green", hex: "#A9C39B", family: "solid" },
  { code: "H102", name: "Forest Green", hex: "#356B2D", family: "solid" },
  { code: "H103", name: "Yellow", hex: "#FFE660", family: "solid" },
  { code: "H104", name: "Lime Green", hex: "#BCD122", family: "solid" },
  { code: "H105", name: "Peach", hex: "#FFAC78", family: "solid" },
  { code: "H106", name: "Lavender", hex: "#CCC5ED", family: "solid" },
  { code: "H107", name: "Sky Blue", hex: "#6A87C1", family: "solid" },
  { code: "H108", name: "Aubergine", hex: "#2A2536", family: "solid" },
  { code: "H109", name: "Cloudy Grey", hex: "#8A847F", family: "solid" },
  { code: "H110", name: "Matcha", hex: "#838956", family: "solid" },
  { code: "H111", name: "Dark Blush", hex: "#835854", family: "solid" },
  { code: "H112", name: "Blush", hex: "#AD8A82", family: "solid" },
  { code: "H113", name: "Aqua", hex: "#5F887B", family: "solid" },
  { code: "H114", name: "Cherry Red", hex: "#9A2C31", family: "solid" },
  { code: "H115", name: "Bright Green", hex: "#6E975F", family: "solid" },
  { code: "H116", name: "Midnight Blue", hex: "#222838", family: "solid" },
  { code: "H117", name: "Taupe Grey", hex: "#777169", family: "solid" },
  { code: "H118", name: "Maroon Red", hex: "#612932", family: "solid" },
  { code: "H119", name: "Sky Blue Clear", hex: "#4167B4", family: "translucent" },
];

export const ARTKAL_S_COLORS: BeadColor[] = [
  { code: "S01", name: "White", hex: "#FFFFFF", family: "solid" },
  { code: "S02", name: "Burning Sand", hex: "#FFA38B", family: "solid" },
  { code: "S03", name: "Tangerine", hex: "#FF8200", family: "solid" },
  { code: "S04", name: "Orange", hex: "#FA4616", family: "solid" },
  { code: "S05", name: "Tall Poppy", hex: "#EE2737", family: "solid" },
  { code: "S06", name: "Raspberry Pink", hex: "#EF64A2", family: "solid" },
  { code: "S07", name: "Gray", hex: "#97999B", family: "solid" },
  { code: "S08", name: "Emerald", hex: "#26D07C", family: "solid" },
  { code: "S09", name: "Dark Green", hex: "#007371", family: "solid" },
  { code: "S10", name: "Baby Blue", hex: "#56B7E6", family: "solid" },
  { code: "S11", name: "Dark Blue", hex: "#0050B5", family: "solid" },
  { code: "S12", name: "Pastel Lavender", hex: "#9063CD", family: "solid" },
  { code: "S13", name: "Black", hex: "#000000", family: "solid" },
  { code: "S14", name: "Sandstorm", hex: "#FDDA24", family: "solid" },
  { code: "S15", name: "Redwood", hex: "#A72B2A", family: "solid" },
  { code: "S16", name: "Brown", hex: "#674736", family: "solid" },
  { code: "S17", name: "Light Brown", hex: "#7B4D35", family: "solid" },
  { code: "S18", name: "Sand", hex: "#EAA794", family: "solid" },
  { code: "S19", name: "Bubble Gum", hex: "#F8C1B8", family: "solid" },
  { code: "S20", name: "Green", hex: "#249E6B", family: "solid" },
  { code: "S21", name: "Pastel Green", hex: "#93C90E", family: "solid" },
  { code: "S22", name: "Purple", hex: "#483698", family: "solid" },
  { code: "S23", name: "Royal Purple", hex: "#7D55C7", family: "solid" },
  { code: "S24", name: "True Blue", hex: "#1164C9", family: "solid" },
  { code: "S25", name: "Hot Pink", hex: "#EF60A3", family: "solid" },
  { code: "S26", name: "Magenta", hex: "#F04E98", family: "solid" },
  { code: "S27", name: "Yellow", hex: "#FFC72C", family: "solid" },
  { code: "S28", name: "Lily Pink", hex: "#EF95CF", family: "solid" },
  { code: "S29", name: "Pastel Yellow", hex: "#FBDB65", family: "solid" },
  { code: "S30", name: "Shadow Green", hex: "#A4E6E8", family: "solid" },
  { code: "S31", name: "Sea Mist", hex: "#B5E3D8", family: "solid" },
  { code: "S32", name: "Beeswax", hex: "#FECB8B", family: "solid" },
  { code: "S33", name: "Maverick", hex: "#C5B4E3", family: "solid" },
  { code: "S34", name: "Red", hex: "#D50032", family: "solid" },
  { code: "S35", name: "Mona Lisa", hex: "#F7CED7", family: "solid" },
  { code: "S36", name: "Old Pink", hex: "#E06287", family: "solid" },
  { code: "S37", name: "Blue-Green", hex: "#8BD3E6", family: "solid" },
  { code: "S38", name: "Burgundy", hex: "#BC204B", family: "solid" },
  { code: "S39", name: "Yellow Orange", hex: "#FF7F41", family: "solid" },
  { code: "S40", name: "Carnation Pink", hex: "#F99FC9", family: "solid" },
  { code: "S41", name: "Copper", hex: "#9A5516", family: "metallic" },
  { code: "S42", name: "Silver", hex: "#A09F9D", family: "metallic" },
  { code: "S43", name: "Dark Gray", hex: "#75787B", family: "solid" },
  { code: "S44", name: "Sky Blue", hex: "#9BCBEB", family: "solid" },
  { code: "S45", name: "Medium Turquoise", hex: "#00B2A9", family: "solid" },
  { code: "S46", name: "Bright Green", hex: "#8EDD65", family: "solid" },
  { code: "S47", name: "Marigold", hex: "#A6631B", family: "solid" },
  { code: "S48", name: "Corn", hex: "#FFC845", family: "solid" },
  { code: "S49", name: "Mulberry Wood", hex: "#973961", family: "solid" },
  { code: "S50", name: "Mandys Pink", hex: "#FFB3AB", family: "solid" },
  { code: "S51", name: "Spring Sun", hex: "#FFF8DB", family: "solid" },
  { code: "S52", name: "Picasso", hex: "#F8E08E", family: "solid" },
  { code: "S53", name: "Blue Enchantress", hex: "#62A0E6", family: "solid" },
  { code: "S54", name: "Light Blue", hex: "#0090DA", family: "solid" },
  { code: "S55", name: "Pistachio", hex: "#ADDC91", family: "solid" },
  { code: "S56", name: "Bright Carrot", hex: "#FF6A39", family: "solid" },
  { code: "S57", name: "Buccaneer", hex: "#B33D26", family: "solid" },
  { code: "S58", name: "Paprika", hex: "#BA0C2F", family: "solid" },
  { code: "S59", name: "Butterfly Bush", hex: "#5949A7", family: "solid" },
  { code: "S60", name: "Lavender", hex: "#9678D3", family: "solid" },
  { code: "S61", name: "Key Lemon Pie", hex: "#E6DE77", family: "solid" },
  { code: "S62", name: "Green Tea", hex: "#007C58", family: "solid" },
  { code: "S63", name: "Metallic Gold", hex: "#4C5914", family: "metallic" },
  { code: "S64", name: "Black Rock", hex: "#2C2D65", family: "solid" },
  { code: "S65", name: "Canary", hex: "#F0EC74", family: "solid" },
  { code: "S66", name: "Blaze Orange", hex: "#EE5340", family: "solid" },
  { code: "S67", name: "Vanilla", hex: "#ECC3B2", family: "solid" },
  { code: "S68", name: "Tan", hex: "#E7B78A", family: "solid" },
  { code: "S69", name: "Mine Shaft", hex: "#212721", family: "solid" },
  { code: "S70", name: "Dark Algae", hex: "#BABC16", family: "solid" },
  { code: "S71", name: "Jade Green", hex: "#008522", family: "solid" },
  { code: "S72", name: "Light Sea Blue", hex: "#67D9DF", family: "solid" },
  { code: "S73", name: "Steel Blue", hex: "#48A9C5", family: "solid" },
  { code: "S74", name: "Azure", hex: "#04A9C7", family: "solid" },
  { code: "S75", name: "Dark Steel Blue", hex: "#0085AD", family: "solid" },
  { code: "S76", name: "Sea Blue", hex: "#00A7B5", family: "solid" },
  { code: "S77", name: "Ghost White", hex: "#D9D9D6", family: "solid" },
  { code: "S78", name: "Ash Gray", hex: "#C8C9C7", family: "solid" },
  { code: "S79", name: "Light Gray", hex: "#B1B3B3", family: "solid" },
  { code: "S80", name: "Dark Olive", hex: "#A2A569", family: "solid" },
  { code: "S81", name: "Deer", hex: "#D5A286", family: "solid" },
  { code: "S82", name: "Clay", hex: "#C58B68", family: "solid" },
  { code: "S83", name: "Sienna", hex: "#B15533", family: "solid" },
  { code: "S84", name: "Deep Chestnut", hex: "#AB5C57", family: "solid" },
  { code: "S85", name: "Red Wine", hex: "#8A2A2B", family: "solid" },
  { code: "S86", name: "Goldenrod", hex: "#F29D04", family: "solid" },
  { code: "S87", name: "Coral Red", hex: "#FF808B", family: "solid" },
  { code: "S88", name: "Dark Pink", hex: "#DA1884", family: "solid" },
  { code: "S89", name: "Charcoal Gray", hex: "#53565A", family: "solid" },
  { code: "S90", name: "Pastel Orange", hex: "#FFC56E", family: "solid" },
  { code: "S91", name: "Brunswick Green", hex: "#183028", family: "solid" },
  { code: "S92", name: "Dandelion", hex: "#C69214", family: "solid" },
  { code: "S93", name: "Pale Skin", hex: "#EDC8A3", family: "solid" },
  { code: "S94", name: "Warm Blush", hex: "#EAA794", family: "solid" },
  { code: "S95", name: "Salmon", hex: "#E8927C", family: "solid" },
  { code: "S96", name: "Apricot", hex: "#FF8D6D", family: "solid" },
  { code: "S97", name: "Papaya", hex: "#E35205", family: "solid" },
  { code: "S98", name: "Himalaya Blue", hex: "#80B6E8", family: "solid" },
  { code: "S99", name: "Waterfall", hex: "#5CA9CC", family: "solid" },
  { code: "S100", name: "Lagoon", hex: "#5DB3CB", family: "solid" },
  { code: "S101", name: "Electric Blue", hex: "#00A3E1", family: "solid" },
  { code: "S102", name: "Pool Blue", hex: "#0077CF", family: "solid" },
  { code: "S103", name: "Caribbean Blue", hex: "#0067B9", family: "solid" },
  { code: "S104", name: "Deep Water", hex: "#007DBA", family: "solid" },
  { code: "S105", name: "Petrol Blue", hex: "#00859B", family: "solid" },
  { code: "S106", name: "Wedgewood Blue", hex: "#0076A8", family: "solid" },
  { code: "S107", name: "Pond Blue", hex: "#007096", family: "solid" },
  { code: "S108", name: "Seashell Beige", hex: "#E6C78A", family: "solid" },
  { code: "S109", name: "Beige", hex: "#CEB888", family: "solid" },
  { code: "S110", name: "Beach Beige", hex: "#C6AA76", family: "solid" },
  { code: "S111", name: "Caffe Latte", hex: "#A08629", family: "solid" },
  { code: "S112", name: "Oaktree Brown", hex: "#897630", family: "solid" },
  { code: "S113", name: "Khaki", hex: "#C3C6A8", family: "solid" },
  { code: "S114", name: "Light Greengray", hex: "#C0BB87", family: "solid" },
  { code: "S115", name: "Mossy Green", hex: "#B0AA7E", family: "solid" },
  { code: "S116", name: "Earth Green", hex: "#A3AA83", family: "solid" },
  { code: "S117", name: "Sage Green", hex: "#77744D", family: "solid" },
  { code: "S118", name: "Pinetree Green", hex: "#5E6738", family: "solid" },
  { code: "S119", name: "Frosty Blue", hex: "#98DBCE", family: "solid" },
  { code: "S120", name: "Polar Mint", hex: "#9BE3BF", family: "solid" },
  { code: "S121", name: "Celadon Green", hex: "#6BBBAE", family: "solid" },
  { code: "S122", name: "Eucalyptus", hex: "#00BB7E", family: "solid" },
  { code: "S123", name: "Clover Field", hex: "#31B700", family: "solid" },
  { code: "S124", name: "Pooltable Felt", hex: "#035F1D", family: "solid" },
  { code: "S125", name: "Snake Green", hex: "#007864", family: "solid" },
  { code: "S126", name: "Dark Eucalyptus", hex: "#00685E", family: "solid" },
  { code: "S127", name: "Marshmallow Rose", hex: "#DECDE7", family: "solid" },
  { code: "S128", name: "Light Grape", hex: "#C98BDB", family: "solid" },
  { code: "S129", name: "Rosebud Pink", hex: "#DCB6C9", family: "solid" },
  { code: "S130", name: "Fuchsia", hex: "#DD74A1", family: "solid" },
  { code: "S131", name: "Candy Violet", hex: "#AD96DC", family: "solid" },
  { code: "S132", name: "Flamingo", hex: "#EF426F", family: "solid" },
  { code: "S133", name: "Pink Plum", hex: "#C724B1", family: "solid" },
  { code: "S134", name: "Amethyst", hex: "#8031A7", family: "solid" },
  { code: "S135", name: "Moonlight Blue", hex: "#9FAEE5", family: "solid" },
  { code: "S136", name: "Summer Rain", hex: "#B4B2E4", family: "solid" },
  { code: "S137", name: "Azur Blue", hex: "#5F8DDA", family: "solid" },
  { code: "S138", name: "Cornflower Blue", hex: "#5780D2", family: "solid" },
  { code: "S139", name: "Forget Me Not", hex: "#5576D1", family: "solid" },
  { code: "S140", name: "Indigo", hex: "#3C62C3", family: "solid" },
  { code: "S141", name: "Horizon Blue", hex: "#466CCA", family: "solid" },
  { code: "S142", name: "Cobalt", hex: "#365ABD", family: "solid" },
  { code: "S143", name: "Royal Blue", hex: "#1E22AA", family: "solid" },
  { code: "S144", name: "Marine", hex: "#002D72", family: "solid" },
  { code: "S145", name: "Pale Yellow Moss", hex: "#E9E186", family: "solid" },
  { code: "S146", name: "Bloodrose Red", hex: "#8C243D", family: "solid" },
  { code: "S147", name: "Spearmint", hex: "#86C8BC", family: "solid" },
  { code: "S148", name: "Mocha", hex: "#724736", family: "solid" },
  { code: "S149", name: "Creme", hex: "#FCD299", family: "solid" },
  { code: "S150", name: "Iris Violet", hex: "#8B84D7", family: "solid" },
  { code: "S151", name: "Forrest Green", hex: "#335525", family: "solid" },
  { code: "S152", name: "Lilac", hex: "#A7A4E0", family: "solid" },
  { code: "S153", name: "Pale Lilac", hex: "#C6C4EA", family: "solid" },
  { code: "S154", name: "Sahara Sand", hex: "#EBC29D", family: "solid" },
  { code: "S155", name: "Sunkissed Teint", hex: "#C58B68", family: "solid" },
  { code: "S156", name: "Steel Grey", hex: "#63666A", family: "solid" },
  { code: "S157", name: "Iron Grey", hex: "#46494C", family: "solid" },
  { code: "S158", name: "Pepper", hex: "#191D19", family: "solid" },
  { code: "S159", name: "Oslo Gray", hex: "#88888D", family: "solid" },
  { code: "SE01", name: "Extended Pale Blue", hex: "#D1DDE6", family: "solid" },
  { code: "SE02", name: "Extended Light Blue", hex: "#9BB8E3", family: "solid" },
  { code: "SE03", name: "Extended Medium Blue", hex: "#5E8AB4", family: "solid" },
  { code: "SE04", name: "Extended Cyan", hex: "#6AD1E3", family: "solid" },
  { code: "SE05", name: "Extended Teal", hex: "#03C1AA", family: "solid" },
  { code: "SE06", name: "Extended Bright Blue", hex: "#126AD4", family: "solid" },
  { code: "SE07", name: "Extended Dusty Mauve", hex: "#BFA5B8", family: "solid" },
  { code: "SE08", name: "Extended Muted Purple", hex: "#9B7793", family: "solid" },
  { code: "SE09", name: "Extended Dark Plum", hex: "#693C5E", family: "solid" },
  { code: "SE10", name: "Extended Bright Magenta", hex: "#C964CF", family: "solid" },
  { code: "SE11", name: "Extended Deep Magenta", hex: "#AD1AAC", family: "solid" },
  { code: "SE12", name: "Extended Light Orange", hex: "#FFB25B", family: "solid" },
  { code: "SE13", name: "Extended Caramel", hex: "#E6A65D", family: "solid" },
  { code: "SE14", name: "Extended Dark Caramel", hex: "#D38235", family: "solid" },
  { code: "SE15", name: "Extended Burnt Caramel", hex: "#C16C18", family: "solid" },
  { code: "SE16", name: "Extended Light Pink", hex: "#F5B6CD", family: "solid" },
  { code: "SE17", name: "Extended Maroon", hex: "#5D2A2C", family: "solid" },
];

export const ARTKAL_MINI_COLORS: BeadColor[] = [
  { code: "MA1", name: "淡黄色 / Pale Yellow", hex: "#FFF6D4", family: "solid" },
  { code: "MA2", name: "浅黄色 / Light Yellow", hex: "#F6F9E5", family: "solid" },
  { code: "MA3", name: "亮黄色 / Bright Yellow", hex: "#FFFBAA", family: "solid" },
  { code: "MA4", name: "金黄色 / Golden Yellow", hex: "#FFDF58", family: "solid" },
  { code: "MA5", name: "深金黄 / Deep Gold", hex: "#FECF4D", family: "solid" },
  { code: "MA6", name: "橙黄色 / Orange Yellow", hex: "#FFA80C", family: "solid" },
  { code: "MA7", name: "橙色 / Orange", hex: "#FF8837", family: "solid" },
  { code: "MA8", name: "柔和橙 / Soft Orange", hex: "#EAC431", family: "solid" },
  { code: "MA9", name: "浅橙色 / Light Orange", hex: "#F1AA8F", family: "solid" },
  { code: "MA10", name: "深橙色 / Deep Orange", hex: "#FF8F42", family: "solid" },
  { code: "MA11", name: "浅杏色 / Light Apricot", hex: "#FFE1A1", family: "solid" },
  { code: "MA12", name: "杏色 / Apricot", hex: "#F4B39C", family: "solid" },
  { code: "MA13", name: "浅黄橙 / Light Yellow-Orange", hex: "#FFB100", family: "solid" },
  { code: "MA14", name: "红橙色 / Red-Orange", hex: "#FF6510", family: "solid" },
  { code: "MA15", name: "柠檬黄 / Lemon Yellow", hex: "#DAF05C", family: "solid" },
  { code: "MA16", name: "亮柠檬 / Bright Lemon", hex: "#F9FBBE", family: "solid" },
  { code: "MA17", name: "蛋黄色 / Yolk", hex: "#FFD976", family: "solid" },
  { code: "MA18", name: "浅橙棕 / Light Orange-Brown", hex: "#FFCA9A", family: "solid" },
  { code: "MA19", name: "浅红橙 / Light Red-Orange", hex: "#EC7A92", family: "solid" },
  { code: "MA20", name: "蜜黄色 / Honey", hex: "#E5BE55", family: "solid" },
  { code: "MA21", name: "浅蜜黄 / Light Honey", hex: "#FFE596", family: "solid" },
  { code: "MA22", name: "黄绿色 / Yellow-Green", hex: "#F7E898", family: "solid" },
  { code: "MA23", name: "米黄色 / Beige Yellow", hex: "#F0CBB1", family: "solid" },
  { code: "MA24", name: "浅黄绿 / Light Yellow-Green", hex: "#F5FCD1", family: "solid" },
  { code: "MA25", name: "淡黄绿 / Pale Yellow-Green", hex: "#F6D487", family: "solid" },
  { code: "MA26", name: "金色 / Gold", hex: "#FFCB4B", family: "solid" },
  { code: "MB1", name: "黄绿 / Yellow-Green", hex: "#D2E318", family: "solid" },
  { code: "MB2", name: "亮绿 / Bright Green", hex: "#79CD41", family: "solid" },
  { code: "MB3", name: "浅绿 / Light Green", hex: "#82D7A1", family: "solid" },
  { code: "MB4", name: "春绿 / Spring Green", hex: "#65DF4F", family: "solid" },
  { code: "MB5", name: "鲜绿 / Vivid Green", hex: "#5FC873", family: "solid" },
  { code: "MB6", name: "薄荷绿 / Mint", hex: "#49D1AE", family: "solid" },
  { code: "MB7", name: "森林绿 / Forest", hex: "#009696", family: "solid" },
  { code: "MB8", name: "深绿 / Deep Green", hex: "#08774F", family: "solid" },
  { code: "MB9", name: "暗绿 / Dark Green", hex: "#183823", family: "solid" },
  { code: "MB10", name: "柔和绿 / Soft Green", hex: "#83CFC3", family: "solid" },
  { code: "MB11", name: "军绿 / Army Green", hex: "#5A6A27", family: "solid" },
  { code: "MB12", name: "深森林绿 / Deep Forest", hex: "#045F45", family: "solid" },
  { code: "MB13", name: "淡绿 / Pale Green", hex: "#E2FFB3", family: "solid" },
  { code: "MB14", name: "青草绿 / Grass Green", hex: "#9DD12E", family: "solid" },
  { code: "MB15", name: "深青绿 / Deep Teal Green", hex: "#254B3C", family: "solid" },
  { code: "MB16", name: "浅青绿 / Light Teal Green", hex: "#D0FCAD", family: "solid" },
  { code: "MB17", name: "橄榄绿 / Olive", hex: "#8CA12A", family: "solid" },
  { code: "MB18", name: "黄绿亮 / Bright Yellow-Green", hex: "#D2D958", family: "solid" },
  { code: "MB19", name: "翡翠绿 / Emerald", hex: "#49BCA9", family: "solid" },
  { code: "MB20", name: "薄荷淡绿 / Mint Light", hex: "#E8FDEC", family: "solid" },
  { code: "MB21", name: "深蓝绿 / Deep Blue-Green", hex: "#188B81", family: "solid" },
  { code: "MB22", name: "深青 / Deep Teal", hex: "#0C5C5B", family: "solid" },
  { code: "MB23", name: "橄榄棕 / Olive Brown", hex: "#3D461B", family: "solid" },
  { code: "MB24", name: "柔和黄绿 / Soft Yellow-Green", hex: "#EAFCB6", family: "solid" },
  { code: "MB25", name: "墨绿 / Ink Green", hex: "#538771", family: "solid" },
  { code: "MB26", name: "棕绿 / Brown-Green", hex: "#8A7A40", family: "solid" },
  { code: "MB27", name: "淡灰绿 / Pale Gray-Green", hex: "#D2DEB6", family: "solid" },
  { code: "MB28", name: "浅薄荷绿 / Light Mint", hex: "#9FF4C2", family: "solid" },
  { code: "MB29", name: "黄绿色 / Yellow-Green", hex: "#BBD747", family: "solid" },
  { code: "MB30", name: "淡黄绿 / Pale Yellow-Green", hex: "#F5FFE6", family: "solid" },
  { code: "MB31", name: "浅草绿 / Light Grass", hex: "#BFE1C2", family: "solid" },
  { code: "MB32", name: "灰绿 / Gray-Green", hex: "#9FBA5C", family: "solid" },
  { code: "MC1", name: "淡白绿 / Pale White-Green", hex: "#D5E3DE", family: "solid" },
  { code: "MC2", name: "亮青 / Bright Cyan", hex: "#BBF1F4", family: "solid" },
  { code: "MC3", name: "浅青 / Light Cyan", hex: "#73C0DF", family: "solid" },
  { code: "MC4", name: "天青 / Sky Cyan", hex: "#33B3E1", family: "solid" },
  { code: "MC5", name: "深天青 / Deep Sky", hex: "#00A3CA", family: "solid" },
  { code: "MC6", name: "浅蓝 / Light Blue", hex: "#58A0D9", family: "solid" },
  { code: "MC7", name: "中蓝 / Medium Blue", hex: "#0588CC", family: "solid" },
  { code: "MC8", name: "深蓝 / Deep Blue", hex: "#005F9E", family: "solid" },
  { code: "MC9", name: "皇蓝 / Royal Blue", hex: "#086FB9", family: "solid" },
  { code: "MC10", name: "天空蓝 / Sky Blue", hex: "#52B4E0", family: "solid" },
  { code: "MC11", name: "松绿蓝 / Pine Blue", hex: "#00A9B9", family: "solid" },
  { code: "MC12", name: "深夜蓝 / Midnight Blue", hex: "#1C375A", family: "solid" },
  { code: "MC13", name: "浅蓝白 / Light Blue-White", hex: "#CEE0F0", family: "solid" },
  { code: "MC14", name: "淡青绿 / Pale Cyan-Green", hex: "#EBF5F4", family: "solid" },
  { code: "MC15", name: "青蓝 / Cyan Blue", hex: "#00AAAD", family: "solid" },
  { code: "MC16", name: "深蓝紫 / Deep Blue-Purple", hex: "#004C7D", family: "solid" },
  { code: "MC17", name: "亮青蓝 / Bright Cyan-Blue", hex: "#5BD4F6", family: "solid" },
  { code: "MC18", name: "深灰蓝 / Deep Gray-Blue", hex: "#36515C", family: "solid" },
  { code: "MC19", name: "深青蓝 / Deep Cyan-Blue", hex: "#0F909D", family: "solid" },
  { code: "MC20", name: "深海蓝 / Deep Sea Blue", hex: "#0084B7", family: "solid" },
  { code: "MC21", name: "淡蓝 / Pale Blue", hex: "#DDECFA", family: "solid" },
  { code: "MC22", name: "灰蓝 / Gray Blue", hex: "#84BAC2", family: "solid" },
  { code: "MC23", name: "浅蓝 / Light Blue", hex: "#CBDBDB", family: "solid" },
  { code: "MC24", name: "空蓝 / Air Blue", hex: "#88BDE2", family: "solid" },
  { code: "MC25", name: "浅青蓝 / Light Cyan-Blue", hex: "#B3ECE0", family: "solid" },
  { code: "MC26", name: "深青蓝 / Deep Cyan-Blue", hex: "#3E9EBF", family: "solid" },
  { code: "MC27", name: "淡紫蓝 / Pale Purple-Blue", hex: "#E9F0F3", family: "solid" },
  { code: "MC28", name: "灰紫蓝 / Gray Purple-Blue", hex: "#C2CDE3", family: "solid" },
  { code: "MC29", name: "深紫蓝 / Deep Purple-Blue", hex: "#586B8F", family: "solid" },
  { code: "MD1", name: "浅紫 / Light Purple", hex: "#7292E2", family: "solid" },
  { code: "MD2", name: "紫罗兰 / Violet", hex: "#6E8CCC", family: "solid" },
  { code: "MD3", name: "中紫 / Medium Purple", hex: "#13419A", family: "solid" },
  { code: "MD4", name: "深紫 / Deep Purple", hex: "#1E3175", family: "solid" },
  { code: "MD5", name: "品红 / Magenta", hex: "#B850B2", family: "solid" },
  { code: "MD6", name: "浅紫罗兰 / Light Violet", hex: "#AD92E9", family: "solid" },
  { code: "MD7", name: "葡萄紫 / Grape", hex: "#5F2D91", family: "solid" },
  { code: "MD8", name: "淡紫 / Pale Purple", hex: "#D7CDF1", family: "solid" },
  { code: "MD9", name: "浅葡萄紫 / Light Grape", hex: "#BDB2E6", family: "solid" },
  { code: "MD10", name: "深葡萄 / Deep Grape", hex: "#251B58", family: "solid" },
  { code: "MD11", name: "灰紫 / Gray Purple", hex: "#A2BBE7", family: "solid" },
  { code: "MD12", name: "玫瑰紫 / Rose Purple", hex: "#CF8BBE", family: "solid" },
  { code: "MD13", name: "深品红 / Deep Magenta", hex: "#B80096", family: "solid" },
  { code: "MD14", name: "紫红 / Purple-Red", hex: "#A137A7", family: "solid" },
  { code: "MD15", name: "深蓝紫 / Deep Blue-Purple", hex: "#4A388A", family: "solid" },
  { code: "MD16", name: "淡紫白 / Pale Purple-White", hex: "#DCE8F6", family: "solid" },
  { code: "MD17", name: "淡蓝紫 / Pale Blue-Purple", hex: "#AECEF0", family: "solid" },
  { code: "MD18", name: "深紫罗兰 / Deep Violet", hex: "#B38EDB", family: "solid" },
  { code: "MD19", name: "淡玫瑰紫 / Pale Rose Purple", hex: "#E8D2EA", family: "solid" },
  { code: "MD20", name: "兰紫 / Orchid Purple", hex: "#B460C3", family: "solid" },
  { code: "MD21", name: "深兰紫 / Deep Orchid", hex: "#842A94", family: "solid" },
  { code: "MD22", name: "深紫蓝 / Deep Purple-Blue", hex: "#4B5E9E", family: "solid" },
  { code: "MD23", name: "浅紫白 / Light Purple-White", hex: "#D6D2E2", family: "solid" },
  { code: "MD24", name: "紫蓝 / Purple-Blue", hex: "#7776D1", family: "solid" },
  { code: "MD25", name: "深紫蓝 / Deep Purple-Blue", hex: "#3837A8", family: "solid" },
  { code: "MD26", name: "淡紫粉 / Pale Purple-Pink", hex: "#DDC8DD", family: "solid" },
  { code: "ME1", name: "浅肉色 / Light Skin", hex: "#FDD6C9", family: "solid" },
  { code: "ME2", name: "淡粉红 / Pale Pink", hex: "#FFD8F4", family: "solid" },
  { code: "ME3", name: "浅粉紫 / Light Pink-Purple", hex: "#FFA0C3", family: "solid" },
  { code: "ME4", name: "粉红 / Pink", hex: "#F67AAB", family: "solid" },
  { code: "ME5", name: "亮粉红 / Bright Pink", hex: "#DA5B95", family: "solid" },
  { code: "ME6", name: "深粉红 / Deep Pink", hex: "#FF4B78", family: "solid" },
  { code: "ME7", name: "暗粉红 / Dark Pink", hex: "#9E156B", family: "solid" },
  { code: "ME8", name: "浅粉 / Light Pink", hex: "#FFE1E6", family: "solid" },
  { code: "ME9", name: "兰粉 / Orchid Pink", hex: "#F378CA", family: "solid" },
  { code: "ME10", name: "深兰粉 / Deep Orchid Pink", hex: "#BE316D", family: "solid" },
  { code: "ME11", name: "浅肤色 / Light Skin", hex: "#FFE8DA", family: "solid" },
  { code: "ME12", name: "淡肤色 / Pale Skin", hex: "#FFA5C6", family: "solid" },
  { code: "ME13", name: "深品红 / Deep Magenta", hex: "#B53883", family: "solid" },
  { code: "ME14", name: "浅杏粉 / Light Apricot Pink", hex: "#FFDDC7", family: "solid" },
  { code: "ME15", name: "浅粉肤 / Light Pink Skin", hex: "#E5C6D0", family: "solid" },
  { code: "ME16", name: "淡米白 / Pale Cream", hex: "#F9F2EB", family: "solid" },
  { code: "ME17", name: "淡粉白 / Pale Pink-White", hex: "#E7DCE6", family: "solid" },
  { code: "ME18", name: "浅粉白 / Light Pink-White", hex: "#FFD3E6", family: "solid" },
  { code: "ME19", name: "淡粉 / Pale Pink", hex: "#FFD5EC", family: "solid" },
  { code: "ME20", name: "灰粉 / Gray Pink", hex: "#F3DCE8", family: "solid" },
  { code: "ME21", name: "棕粉 / Brown Pink", hex: "#BD9CA3", family: "solid" },
  { code: "ME22", name: "灰棕粉 / Gray Brown Pink", hex: "#C578A5", family: "solid" },
  { code: "ME23", name: "深灰粉 / Deep Gray Pink", hex: "#A37A9B", family: "solid" },
  { code: "ME24", name: "浅紫粉 / Light Purple Pink", hex: "#F4E8FF", family: "solid" },
  { code: "MF1", name: "浅红 / Light Red", hex: "#FF7F67", family: "solid" },
  { code: "MF2", name: "深红 / Deep Red", hex: "#FF5D46", family: "solid" },
  { code: "MF3", name: "砖红 / Brick Red", hex: "#E3564A", family: "solid" },
  { code: "MF4", name: "亮红 / Bright Red", hex: "#C7270D", family: "solid" },
  { code: "MF5", name: "正红 / True Red", hex: "#BE0A27", family: "solid" },
  { code: "MF6", name: "深棕红 / Deep Brown Red", hex: "#83411E", family: "solid" },
  { code: "MF7", name: "暗棕红 / Dark Brown Red", hex: "#730037", family: "solid" },
  { code: "MF8", name: "深红 / Dark Red", hex: "#AB0022", family: "solid" },
  { code: "MF9", name: "浅红 / Light Red", hex: "#DE7995", family: "solid" },
  { code: "MF10", name: "棕红 / Brown Red", hex: "#AB613C", family: "solid" },
  { code: "MF11", name: "深棕 / Deep Brown", hex: "#5C2929", family: "solid" },
  { code: "MF12", name: "玫瑰红 / Rose Red", hex: "#F34461", family: "solid" },
  { code: "MF13", name: "番茄红 / Tomato Red", hex: "#C64239", family: "solid" },
  { code: "MF14", name: "浅粉红 / Light Pink-Red", hex: "#FFA5BB", family: "solid" },
  { code: "MF15", name: "深绯红 / Deep Crimson", hex: "#BC0018", family: "solid" },
  { code: "MF16", name: "浅肉红 / Light Flesh Red", hex: "#FFD7CB", family: "solid" },
  { code: "MF17", name: "浅棕红 / Light Brown Red", hex: "#F19D8A", family: "solid" },
  { code: "MF18", name: "棕红 / Brown Red", hex: "#DC7B45", family: "solid" },
  { code: "MF19", name: "深棕红 / Deep Brown Red", hex: "#C74651", family: "solid" },
  { code: "MF20", name: "灰棕红 / Gray Brown Red", hex: "#D8A89E", family: "solid" },
  { code: "MF21", name: "浅粉棕 / Light Pink-Brown", hex: "#EB9DB9", family: "solid" },
  { code: "MF22", name: "淡粉棕 / Pale Pink-Brown", hex: "#FFD4D4", family: "solid" },
  { code: "MF23", name: "珊瑚红 / Coral Red", hex: "#EA8474", family: "solid" },
  { code: "MF24", name: "玫瑰红 / Rose Red", hex: "#F7C1C5", family: "solid" },
  { code: "MF25", name: "砖红 / Brick Red", hex: "#FC5768", family: "solid" },
  { code: "MG1", name: "淡肤色 / Pale Skin", hex: "#FFE7C8", family: "solid" },
  { code: "MG2", name: "浅肤色 / Light Skin", hex: "#FFD6C3", family: "solid" },
  { code: "MG3", name: "肤色 / Skin", hex: "#EEB694", family: "solid" },
  { code: "MG4", name: "深肤色 / Deep Skin", hex: "#D9A58C", family: "solid" },
  { code: "MG5", name: "棕金 / Brown Gold", hex: "#F49630", family: "solid" },
  { code: "MG6", name: "深棕金 / Deep Brown Gold", hex: "#F19937", family: "solid" },
  { code: "MG7", name: "深棕 / Deep Brown", hex: "#AC745B", family: "solid" },
  { code: "MG8", name: "深棕色 / Dark Brown", hex: "#694A42", family: "solid" },
  { code: "MG9", name: "浅棕 / Light Brown", hex: "#F7CC9D", family: "solid" },
  { code: "MG10", name: "棕色 / Brown", hex: "#C7832F", family: "solid" },
  { code: "MG11", name: "浅棕金 / Light Brown Gold", hex: "#D3C391", family: "solid" },
  { code: "MG12", name: "浅橙棕 / Light Orange Brown", hex: "#E6B986", family: "solid" },
  { code: "MG13", name: "棕红 / Brown Red", hex: "#C67B4F", family: "solid" },
  { code: "MG14", name: "深棕 / Deep Brown", hex: "#8D6242", family: "solid" },
  { code: "MG15", name: "淡米黄 / Pale Cream Yellow", hex: "#F6F7E2", family: "solid" },
  { code: "MG16", name: "浅米肤 / Light Cream Skin", hex: "#F2E7D7", family: "solid" },
  { code: "MG17", name: "深棕灰 / Deep Brown Gray", hex: "#786562", family: "solid" },
  { code: "MG18", name: "浅肤米 / Light Skin Cream", hex: "#FEF5EB", family: "solid" },
  { code: "MG19", name: "橙棕 / Orange Brown", hex: "#F0AB47", family: "solid" },
  { code: "MG20", name: "深橙棕 / Deep Orange Brown", hex: "#AE6949", family: "solid" },
  { code: "MG21", name: "棕灰 / Brown Gray", hex: "#BF8C6E", family: "solid" },
  { code: "MH1", name: "透明 / Transparent", hex: "#FFFFFF", family: "translucent" },
  { code: "MH2", name: "极白 / Pure White", hex: "#FFFFFF", family: "solid" },
  { code: "MH3", name: "浅灰 / Light Gray", hex: "#9B9B9B", family: "solid" },
  { code: "MH4", name: "中灰 / Medium Gray", hex: "#6D6D6D", family: "solid" },
  { code: "MH5", name: "深灰 / Deep Gray", hex: "#4D4D4D", family: "solid" },
  { code: "MH6", name: "深深灰 / Very Dark Gray", hex: "#3A3A3A", family: "solid" },
  { code: "MH7", name: "黑色 / Black", hex: "#000000", family: "solid" },
  { code: "MH8", name: "淡棕灰 / Pale Brown Gray", hex: "#FFF0F1", family: "solid" },
  { code: "MH9", name: "淡灰紫 / Pale Gray Purple", hex: "#E3E6DF", family: "solid" },
  { code: "MH10", name: "浅灰 / Light Gray", hex: "#E2E0E7", family: "solid" },
  { code: "MH11", name: "灰色 / Gray", hex: "#BCB8B5", family: "solid" },
  { code: "MH12", name: "淡米白 / Pale Cream White", hex: "#F7F3E1", family: "solid" },
  { code: "MH13", name: "淡紫灰 / Pale Purple Gray", hex: "#EADDC8", family: "solid" },
  { code: "MH14", name: "灰绿 / Gray Green", hex: "#B8C8C5", family: "solid" },
  { code: "MH15", name: "淡灰绿 / Pale Gray Green", hex: "#99ABAC", family: "solid" },
  { code: "MH16", name: "深灰 / Dark Gray", hex: "#444236", family: "solid" },
  { code: "MH17", name: "淡灰 / Pale Gray", hex: "#FAFBF5", family: "solid" },
  { code: "MH18", name: "淡白 / Pale White", hex: "#FEFEEE", family: "solid" },
  { code: "MH19", name: "淡米灰 / Pale Cream Gray", hex: "#FBF2E4", family: "solid" },
  { code: "MH20", name: "中灰 / Medium Gray", hex: "#9EAEAD", family: "solid" },
  { code: "MH21", name: "淡黄白 / Pale Yellow White", hex: "#FDFFF2", family: "solid" },
  { code: "MH22", name: "浅灰 / Light Gray", hex: "#EDEDE7", family: "solid" },
  { code: "MH23", name: "灰绿 / Gray Green", hex: "#B4B8A7", family: "solid" },
  { code: "MM1", name: "灰绿 / Gray Green", hex: "#AEBBA8", family: "solid" },
  { code: "MM2", name: "深灰绿 / Deep Gray Green", hex: "#729376", family: "solid" },
  { code: "MM3", name: "蓝灰绿 / Blue Gray Green", hex: "#6A8890", family: "solid" },
  { code: "MM4", name: "淡棕灰 / Pale Brown Gray", hex: "#BEB39D", family: "solid" },
  { code: "MM5", name: "灰棕 / Gray Brown", hex: "#B8B78C", family: "solid" },
  { code: "MM6", name: "深灰棕 / Deep Gray Brown", hex: "#B2AC93", family: "solid" },
  { code: "MM7", name: "灰棕 / Gray Brown", hex: "#BC9F94", family: "solid" },
  { code: "MM8", name: "棕灰 / Brown Gray", hex: "#968381", family: "solid" },
  { code: "MM9", name: "深棕 / Deep Brown", hex: "#B39D88", family: "solid" },
  { code: "MM10", name: "紫灰 / Purple Gray", hex: "#B796A3", family: "solid" },
  { code: "MM11", name: "深紫灰 / Deep Purple Gray", hex: "#B096B9", family: "solid" },
  { code: "MM12", name: "深棕灰 / Deep Brown Gray", hex: "#685951", family: "solid" },
  { code: "MM13", name: "棕色 / Brown", hex: "#C79582", family: "solid" },
  { code: "MM14", name: "深棕 / Deep Brown", hex: "#CA694F", family: "solid" },
  { code: "MM15", name: "深灰 / Deep Gray", hex: "#929FA9", family: "solid" },
];

export const BRANDS = {
  perler: { label: "Perler", pitchMm: 5, colors: PERLER_COLORS },
  mard221: { label: "MARD 221", pitchMm: 5, colors: MARD221_COLORS },
  mard291: { label: "MARD 291", pitchMm: 2.6, colors: MARD291_COLORS },
  coco291: { label: "COCO 291", pitchMm: 2.6, colors: COCO291_COLORS },
  hama: { label: "Hama", pitchMm: 5, colors: HAMA_COLORS },
  artkalS: { label: "Artkal S", pitchMm: 5, colors: ARTKAL_S_COLORS },
  artkalMini: { label: "Artkal Mini", pitchMm: 2.6, colors: ARTKAL_MINI_COLORS },
} as const satisfies Record<string, Brand>;

export type BrandId = keyof typeof BRANDS;
